#config_version=5
event_player:
  s_start_button_active: sw_add_player
  mode_attract_started: mode_attract_started_lights_off

show_player:
  mode_attract_started: 
    incand_off:
      action: play
      loops: -1
    attract_display_loop:
      action: play
      loops: -1
    attract_light_loop:
      action: play
      loops: -1
  mode_attract_will_stop:
    attract_display_loop:
      action: stop
    attract_light_loop:
      action: stop

sound_player:
  mode_attract_started:
    theme_song:
      action: play
      loops: -1
  mode_attract_will_stop:
    theme_song:
      action: stop


# light_player:
#   mode_attract_started:
#     l_side_drain:
#       color: on
#     l_side_top_right:
#       color: on
#     l_side_top_left:
#       color: on
#     l_side_right:
#       color: on
#     l_side_left:
#       color: on
#     l_spot_sling_right:
#       color: on
#     l_spot_sling_left:
#       color: on
#     l_sling_right:
#       color: on
#     l_sling_left:
#       color: on
#     l_flip_lane_right:
#       color: on
#     l_flip_lane_left:
#       color: on
#     l_pop_bottom:
#       color: on
#     l_pop_left:
#       color: on
#     l_pop_right:
#       color: on
#   mode_attract_started_lights_off:
#     l_side_drain:
#       color: off
#     l_side_top_right:
#       color: off
#     l_side_top_left:
#       color: off
#     l_side_right:
#       color: off
#     l_side_left:
#       color: off
#     l_spot_sling_right:
#       color: off
#     l_spot_sling_left:
#       color: off
#     l_sling_right:
#       color: off
#     l_sling_left:
#       color: off
#     l_flip_lane_right:
#       color: off
#     l_flip_lane_left:
#       color: off
#     l_pop_bottom:
#       color: off
#     l_pop_left:
#       color: off
#     l_pop_right:
#       color: off