#config_version=6

mode_settings:
  selectable_items:
    - title
    - credits
    - last_scores_1p{machine.player1_score and not machine.player2_score}
    - last_scores_2p{machine.player2_score and not machine.player3_score}
    - last_scores_3p{machine.player3_score and not machine.player4_score}
    - last_scores_4p{machine.player4_score}
    - thanks_to
  next_item_events: s_fl_right_a_active, timer_attract_carousel_timer_complete
  previous_item_events: s_fl_left_a_active

event_player:
  s_start_button_active: sw_add_player

slide_player:
  mode_attract_started: attract

sound_player:
  mode_attract_started:
    theme_song:
      bus: music

show_player:
  mode_attract_started:
    attract_light_loop:
      action: play
      loops: -1
  mode_attract_will_stop:
    attract_light_loop:
      action: stop

timers:
  attract_carousel_timer:
    end_value: 1
    tick_interval: 5s
    start_running: true
    control_events:
      - event: item_highlighted
        action: restart
      - event: flipper_cradle
        action: stop
      - event: flipper_cradle_release
        action: restart