#config_version=6
mode:           
  start_events: start_mode_field_hogwarts_castle_level2
  stop_events: stop_mode_field_hogwarts_castle_level2
  priority: 300

shots:
  # This shot is a drop-target. The shot is here for mode progression through shot_profiles_states. 
  # Also the LED light is controlled through shot_profiles_states. A Drop-Target itself has no light config.
  sh_drop1_castle_door_lvl2:
    enable_events: mode_field_hogwarts_castle_level2_started
    disable_events: mode_field_hogwarts_castle_level2_will_stop
    restart_events: ce_restart_sh_drop1_castle_door_lvl2
    advance_events: ce_advance_sh_drop1_castle_door_lvl2
    profile: sp_drop1_castle_door_lvl2
    show_tokens:
      led: l_ws2812_castle_door
      color_name: flames
  # This shot is the shot after the drop target. It goes into the subway_ball_device.
  sh_hogwarts_castle_entrance_lvl2:
    enable_events: mode_field_hogwarts_castle_level2_started
    disable_events: mode_field_hogwarts_castle_level2_will_stop
    hit_events: sh_core_castle_main_entrance_hit
    profile: sp_castle_main_entrance_lvl2

shot_profiles:
  sp_drop1_castle_door_lvl2:
    advance_on_hit: false
    states:
      - name: first_unlit
        show: flames
        sync_ms: 500
      - name: last_unlit
        show: flames
        sync_ms: 500
      - name: first_lit
        show: flash_normal
        sync_ms: 500
      - name: last_unlit
        show: flash_normal
        sync_ms: 500
      - name: open
        show: flash_heartbeat
        sync_ms: 500
  sp_castle_main_entrance_lvl2:
    advance_on_hit: false
    states:
      - name: lit

# Multiball_locks and multiballs will be handeled by global_hogwarts_castle mode.
# That way we can stop this mode and start a mission mode or the next hogwarts_castle_level mode.