#config_version=5
shows:

  flash_slow:
    - duration: 0.5
      lights:
        (led):
          color: (color_name)
          fade: 0.5
    - duration: 0.5
      lights:
        (led):
          color: stop
          fade: 0.5
              
  flash_normal:
    - duration: 0.25
      lights:
        (led):
          color: (color_name)
          fade: 0.25
    - duration: 0.25
      lights:
        (led):
          color: stop
          fade: 0.25       

  flash_heartbeat:
    - duration: 0.25
      lights:
        (led):
          color: (color_name)
          fade: 0.25
    - duration: 0.25
      lights:
        (led):
          color: stop
          fade: 0.25
  
  blink_once:
    - time: 0
      lights:
        (led):
          color: (color_name)
          fade: 0.25
    - time: +1
      lights:
        (led):
          color: stop
          fade: 0.25

              
  light_on:
    - time: 0
      lights:
        (led):
          color: (color_name)
          fade: 0.25
              
  light_off:
    - time: 0
      lights:
          (led): stop