#config_version=6
shows:

#flashing 20-30ms
#fading 60-100ms - 60 for inserts, 100 for GI

  flash_heartbeat:
    - duration: 0.25
      lights:
        (led):
          color: (color_name)
          fade: 0.25
    - duration: 0.25
      lights:
        (led):
          color: stop
          fade: 0.25
  flames:
    - duration: 0.25
      lights:
        (led):
          color: (color_name)
          fade: 0.25
    - duration: 0.1
      lights:
        (led):
          color: stop
          fade: 0.1
    - duration: 0.25
      lights:
        (led):
          color: (color_name)
          fade: 0.25
    - duration: 0.1
      lights:
        (led):
          color: stop
          fade: 0.1
          
  blink_once:
    - time: 0
      lights:
        (led):
          color: (color_name)
          fade: 0.25
    - time: "+1"
      lights:
        (led):
          color: stop
          fade: 0.25

              
  light_on:
    - time: 0
      lights:
        (led):
          color: (color_name)
          fade: 0.25
              
  light_off:
    - time: 0
      lights:
          (led): stop