#config_version=5
mode:           
  start_events: start_mode_field_hogwarts_castle_level1
  stop_events: stop_mode_field_hogwarts_castle_level1
  priority: 300

config:
  - field_hogwarts_castle_level1_slides.yaml




# Subway ball_devices setup (not implemented at the moment)
#
#                                               hogwarts_castle     hagrids_place
#                                                      ↓                 ↓                
#   playfield ←-- left_vuk ←-- left_vuk_buffer ←-- center_div --→ right_vuk_buffer --→ right_vuk --→ playfield
#
# Subway ball_devices setup (implemented)
#
#                                            hogwarts_castle  hagrids_place
#                                                   ↓              ↓                
#   playfield ←-- left_vuk | left_vuk_buffer | center_div | right_vuk_buffer | right_vuk --→ playfield
#
# when 2 ball multiball is started we want from both left and right vuk's a ball.
# one possiblility for a 3 or 4 ball multiball is hagrids_place shot, by which the ball will end straight-on in right_vuk_buffer.
# so to make this all possible we need to make sure that when the first ball is lock in hogwarts castle, trough the center_div, will be routed to the right vuk.
# only then we can enable hagrids_place lock. when we do this earlier and thus the right_vuk_buffer can have already a locked ball, we can never reach the right_vuk anymore.

# so the first ball in hogwarts needs to be routed to the right_vuk
# then enable both hagrids_place and diagon_alley lock
# second ball in hogwarts (which will start the 2-ball multiball) needs to be router to the left_vuk


shots:
  # This shot is a drop-target. The shot is here for controlling led light as drop targets have no light config.
  sh_hogwarts_castle_door_lvl1:
    enable_events: mode_field_hogwarts_castle_level1_started
    disable_events: mode_field_hogwarts_castle_level1_will_stop
    restart_events: ce_restart_sh_hogwarts_castle_door_lvl1
    advance_events: ce_advance_sh_hogwarts_castle_door_lvl1
    profile: sp_hogwarts_castle_door
    show_tokens:
      led: l_ws2812_castle_door
      color_name: flames
  # This shot is the shot after the drop target. It goes into the subway_ball_device.
  sh_hogwarts_castle_entrance_lvl1:
    advance_events: sh_core_castle_main_entrance_hit
    profile: sp_castle_main_entrance

shot_profiles:
  sp_hogwarts_castle_door:
    advance_on_hit: false
    states:
      - name: unlit
        show: flames
        sync_ms: 500
      - name: lit
        show: flash_normal
        sync_ms: 500
      - name: open
        show: flash_heartbeat
        sync_ms: 500
  sp_castle_main_entrance:
    advance_on_hit: false
    states:
      - name: unlit
      - name: lit


multiball_locks:
  mbl_hogwarts_castle_level1_left_vuk:
    enable_events: test_event1
    disable_events: mode_field_hogwarts_castle_level1_will_stop
    balls_to_lock: 1
    locked_ball_counting_strategy: no_virtual
    lock_devices: bd_subway_vuk_left
  mbl_hogwarts_castle_level1_right_vuk:
    enable_events: test_event1
    disable_events: mode_field_hogwarts_castle_level1_will_stop
    balls_to_lock: 1
    locked_ball_counting_strategy: no_virtual
    lock_devices: bd_subway_vuk_right
    
  # # enable these when 2ball right vuk lock is set
  # mbl_hogwarts_castle_level1_hagrids_place:
  #   balls_to_lock: 1
  #   locked_ball_counting_strategy: no_virtual
  #   lock_devices: bd_subway_vuk_right_buffer
  # mbl_hogwarts_castle_level1_diagon_alley:
  #   balls_to_lock: 1
  #   lock_devices: bd_diagon_alley_vuk

multiballs:
  mb_hogwarts_calste_level1_2ball:
    enable_events: test_event1
    disable_events: mode_field_hogwarts_castle_level1_will_stop
    reset_events: reset_mb_hogwarts_calste_level1_2ball
    start_events: test_event2
    ball_count: 3
    ball_count_type: total
    ball_locks: bd_subway_vuk_left, bd_subway_vuk_right
    shoot_again: 1s

  # mb_hogwarts_calste_level1_3ball-multiball:
  #   ball_count: 3
  #   ball_count_type: total
  # mb_hogwarts_calste_level1_4ball-multiball:
  #   ball_count: 4
  #   ball_count_type: total

event_player:
  # First hit door to lit shot, reset bank for next step
  drop_target_bank_dtb_hogwarts_castle_down{device.shots.sh_hogwarts_castle_door_lvl1.state_name=='unlit'}:
    - ce_advance_sh_hogwarts_castle_door_lvl1
    - reset_dropbank_hogwarts_castle
  # Hit door again and let magnet grap the ball, level 1 stays door open
  drop_target_bank_dtb_hogwarts_castle_down{device.shots.sh_hogwarts_castle_door_lvl1.state_name=='lit'}:
    - ce_advance_sh_hogwarts_castle_door_lvl1
    - mag_hogwarts_castle_grab_ball
  sh_hogwarts_castle_entrance_lvl1{device.shots.sh_hogwarts_castle_door_lvl1.state_name=='open'}:
    - ce_restart_sh_hogwarts_castle_door_lvl1
  multiball_lock_mbl_hogwarts_castle_level1_full:
    - start_mb_hogwarts_calste_level1_2ball
#multiball_lock(name)_locked_ball.total_balls_locked of iets
#multiball_lock(name)_full