#config_version=5
mode:           
  start_events: start_mode_field_hogwarts_castle_level3
  stop_events: stop_mode_field_hogwarts_castle_level3
  priority: 300

config:
  - field_hogwarts_castle_level3_slides.yaml

# first time in Hogwarts Castle you get intro about the greatest wizards (maybe at this point you have to choose a house)
# after intro you get an overview of progress, this will be shown everytime afterwards
# at some point you unlock level 2 - You know Who, you learn about voldermort
# at some point you unlock level 3 - Dark Magic, you learn about some dark magic
# at some point you unlock level 4 - Horcrux overview, you learn about horcruxes

#for simplicity each level get its own mode. 
#Eacht new level increase magnet difficulty, first level it done for you, second level you dont have to catch but shoot self, last level you have to catch also.

# hit door to lit
# hit again and let magnet grap the ball
# when grabbed open will be opened
# when shot is made the door will closed
# when missed door will be left open until shot is made
# reset shot
shots:
  sh_castle_door:
    advance_events: sh_core_castle_door_hit
    profile: sp_castle_door
    show_tokens:
      led: l_ws2812_castle_door
      color_name: flames
  sh_castle_main_entrance:
    advance_events: sh_core_castle_main_entrance_hit
    profile: sp_castle_main_entrance

shot_profiles:
  sp_castle_door:
    advance_on_hit: false
    states:
      - name: unlit
        show: flames
        sync_ms: 500
      - name: lit
        show: flash_normal
        sync_ms: 500
      - name: open
        show: flash_heartbeat
        sync_ms: 500
  sp_castle_main_entrance:
    advance_on_hit: false
    states:
      - name: unlit
      - name: lit

state_machines:
  sm_hogwarts_castle_level3:
    starting_state: part1
    persist_state: true
    states:
      part1:
        label: Albus Dumbledore
      part2:
        label: Forbidden Forest
      part3:
        label: You know who
    transitions:
      - source: part1
        target: part2
        events: level_1_part_completed, test_event
      - source: part2
        target: part3
        events: level_1_part_completed, test_event

slide_player:
  # this shows a slide on mode start. This is for test purpuse.
  mode_field_castle_level3_started{device.state_machines.sm_hogwarts_castle_level3.state == 'part1'}: 
    sl_level3_part1:
      expire: 3s
  mode_field_castle_level3_started{device.state_machines.sm_hogwarts_castle_level3.state == 'part2'}: 
    sl_level3_part2:
      expire: 3s
  mode_field_castle_level3_started{device.state_machines.sm_hogwarts_castle_level3.state == 'part3'}: 
    sl_level3_part3:
      expire: 3s
