#config_version=5
mode:           
  start_events: start_mode_field_main_entrance_hall
  stop_events: stop_mode_field_main_entrance_hall
  priority: 300


shot_profiles:
  sp_castle_door:
    advance_on_hit: false
    states:
      - name: unlit
        show: light_off
      - name: lit
        show: flash_normal
      - name: open
  sp_main_entrance_hall:
    advance_on_hit: false
    states:
      - name: open
        show: flash_heartbeat
      - name: active

shots:
  sh_castle_door:
    advance_events: sh_core_castle_door_hit
    profile: sp_castle_door
  sh_main_entrance_hall:
    advance_events: sh_core_main_entrance_hall_hit
    profile: sp_main_entrance_hall

