#config_version=5
#|=================================================================================|#
#| GLOBAL MODE |                                                                   |#
#|=================================================================================|#
#| Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula |#
#| eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient |#
#| montes, nascetur ridiculus mus. Donec quam felis, ultricies nec,                |#
#| pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.            |#
#|=================================================================================|#
#| -- Setup --                                                                     |#
#| Lorum Ipsum                                                                     |#
#|                                                                                 |#
#| -- Achievements --                                                              |#
#| Lorum Ipsum                                                                     |#
#|=================================================================================|#
#| Author       | TP-OPS                                                           |#
#| Release date | 18-04-2020                                                       |#
#| Version      | 1.0.0-dev.1                                                      |#
#|=================================================================================|#
#| -- Version history --                                                           |#
#| xx-xx-2020 | 1.0.0 | First release                                              |#
#|=================================================================================|#

state_machines:
  sm_main_entrance_hall_progress:
    states:
      start:
        label: Greatest Wizards
      level_2:
        label: You Know Who
      level_3:
        label: Dark Magic
      level_4:
        label: Horcrux Overview
    transitions:
      - source: start
        target: level_2
        events: sm_main_entrance_hall_start_completed
      - source: level_2
        target: level_3
        events: sm_main_entrance_hall_level_2_completed
      - source: level_3
        target: level_4
        events: sm_main_entrance_hall_level_3_completed