#config_version=5

# HARDWARE MECHANISM LIMITATIONS
# div_tower_entry (div 1) AND div_tower_pensieve (div 2) ARE ENABLED WHEN MODE field_clock_tower_entrance_hall STARTS
# div_tower_entry (div 1) CAN ONLY BE DEACTIVATED WHEN div_tower_pensieve (div 2) IS DEACTIVE
# div_tower_pensieve (div 2) CAN ONLY BE ACTIVATED WHEN div_tower_entry (div 1) IS ENABLED AND ACTIVE AND WHEN bd_tower HAS A BALL (s_tower)
# div_tower_pensieve (div 2) CAN ONLY BE DEACTIVATED WHEN div_tower_entry (div 1) IS ENABLED AND ACTIVE AND WHEN bd_tower HAS NO BALL (s_tower)

# div 1 deactive  -> div 2 can not be activated   (tower_open thus pensieve_closed)
# div 1 active    -> div 2 can be activated       (tower_closed so pensieve can be opened)
# div 2 deactive  -> div 1 can be deactivated     (pensieve_closed so tower can be opened)
# div 2 active    -> div 1 must be active         (pensieve_open)

# div 1 wil be activated when sh_clock_tower is hit (tower now closed)
# mag_tower will be grabbing when event sh_clock_tower_entry_sp_clock_tower_entry_lit_hit is fired
# when bd_clock_tower did not catch the ball, div 1 will be deactivated when s_wire_ramp_left is active (tower now open)
# when bd_clock_tower did catch the ball, div 2 can be activated (tower still closed)

# is div 2 deactive when bd_tower ejects the ball then div 1 will be deactivated when s_wire_ramp_left is active (tower now open)
# is div 2 active when bd_tower ejects the ball (pensieve_open) then div 2 will be deactivated when s_wire_ramp_right_2 is active (pensieve now closed)

mode:           
  start_events: start_mode_field_clock_tower_entrance_hall
  stop_events: reset_clock_tower_completed
  priority: 300

shots:
  # This shot is used to let the magnet grabbing and can be set to unlit when bd_clock_tower has a ball so the magnet will not be activated again
  sh_clock_tower_entry:
    hit_events: sh_core_clock_tower_entry_hit
    profile: sp_clock_tower_entry
  # This shot is used to activate div 1
  sh_clock_tower:
    hit_events: sh_core_clock_tower_bell_hit
    profile: sp_clock_tower_entry

shot_profiles:
  sp_clock_tower_entry:
    advance_on_hit: false
    states:
      - name: unlit
        show: light_off
      - name: lit
        show: flash_normal

ball_holds:
  bh_clock_tower:
    balls_to_hold: 1
    hold_devices: bd_clock_tower
    release_one_events: release_ball

state_machines:
  sm_clock_tower:
    starting_state: tower_open
    states:
      tower_open:
        label:
      tower_closed:
        label:
      pensieve_open:
        label:
      pensieve_closed:
        label:
    transitions:
      - source: tower_open
        target: tower_closed
        events: diverter_div_tower_entry_activating
      - source: tower_closed
        target: pensieve_closed
        events: diverter_div_tower_pensieve_enabling
      - source: pensieve_closed
        target: pensieve_open
        events: diverter_div_tower_pensieve_activating
      - source: pensieve_open
        target: pensieve_closed
        events: diverter_div_tower_pensieve_deactivating
      - source: pensieve_closed
        target: tower_closed
        events: diverter_div_tower_pensieve_disabling
      - source: tower_closed
        target: tower_open
        events: diverter_div_tower_entry_deactivating

event_player:
  sh_clock_tower_entry_sp_clock_tower_entry_lit_hit: mag_clock_tower_grab_ball
  sh_clock_tower_hit: activate_div_tower_entry