#config_version=5
mode:
  start_events: start_mode_field_orbits
  stop_events: stop_mode_field_orbits, mode_field_orbits_alternative_started
  priority: 300

# DIV Castle MUST BE DEACTIVE WHEN DIV Forrest is ACTIVE
# DIV Forrest WILL BE ACTIVATED BY MODE Forbidden Forrest

# DIV Castle ACTIVE AND DIV Forrest DEACTIVE
# Left orbit big (DIV Castle MUST BE ACTIVATED)
# Right orbit big (DIV Castle MUST BE ACTIVATED)
# Left orbit small (DIV Castle MUST BE DEACTIVE)
# Right orbit small (DIV Castle MUST BE DEACTIVE)

# DIV Forrest ACTIVATED THUS DIV Castle DEACTIVATED
# Forbidden forest vuk
# Left orbit small
# Right orbit small

# My orbit sequence_shots can't be used to activate/deactivate diverter div_castle because both left/right sequence_shots using the same switches and you can not enable or disable these sequence_shots.
# As a solution a normal shot for each orbit lane is created. These shots activates diverter div_castle (through event_player and shot_hit events) and disables each other orbit lane shot (through shot disable_events) so these do not activate the diverter again.
# At the end the sequence_shot_hit or _timeout events deactivate diverter div_castle (through event_player and sequence_shot events) and enables each other orbit lane shots (through shot enable_events) again.

# Left-Right-Big      = sq_shot_orbit_big_left
# Right-Left-Big      = sq_shot_orbit_big_right
# Left-Right-Small    = sq_shot_orbit_small_left

shots:
  sh_orbit_lane_left:
    enable_events: 
      - enable_sh_orbit_lane_left
      - sq_shot_orbit_big_right_hit
      - sq_shot_orbit_big_right_timeout
      - sq_shot_orbit_small_left_hit
      - sq_shot_orbit_small_left_timeout
    disable_events: 
      - sh_orbit_lane_right_hit
      - sh_orbit_lane_castle_hit
    hit_events: 
      - sh_core_orbit_lane_left_hit
  sh_orbit_lane_right:
    enable_events: 
      - enable_sh_orbit_lane_right
      - sq_shot_orbit_big_left_hit
      - sq_shot_orbit_big_left_timeout
      - sq_shot_orbit_small_left_hit
      - sq_shot_orbit_small_left_timeout
    disable_events: 
      - sh_orbit_lane_left_hit
      - sh_orbit_lane_castle_hit
    hit_events:
      - sh_core_orbit_lane_right_hit
  sh_orbit_lane_castle:
    enable_events: 
      - enable_sh_orbit_lane_castle
      - sq_shot_orbit_big_left_hit
      - sq_shot_orbit_big_left_timeout
      - sq_shot_orbit_big_right_hit
      - sq_shot_orbit_big_right_timeout
    disable_events: 
      - sh_orbit_lane_left_hit
      - sh_orbit_lane_right_hit
    hit_events:
      - sh_core_orbit_lane_castle_hit
    
sequence_shots:
  sq_shot_orbit_big_left:
    switch_sequence: s_orbit_left, s_orbit_right
    sequence_timeout: 3s
  sq_shot_orbit_big_right:
    switch_sequence: s_orbit_right, s_orbit_left
    sequence_timeout: 3s
  sq_shot_orbit_small_left:
    switch_sequence: s_div_castle, s_orbit_right
    sequence_timeout: 3s

event_player:
  mode_field_orbits_started:
    - enable_div_castle
    - enable_div_forest
    - enable_sh_orbit_lane_left
    - enable_sh_orbit_lane_right
    - enable_sh_orbit_lane_castle
  stop_mode_field_orbits:
    - deactivate_div_castle
    - deactivate_div_forest
    - disable_div_castle|0.1s
    - disable_div_forest|0.1s
  sh_orbit_lane_left_hit:
    - activate_div_castle
    - deactivate_div_castle|2s
  sh_orbit_lane_right_hit:
    - activate_div_castle
    - deactivate_div_castle|2s