#config_version=5

# Main slide center position is as follows;
# x: left+575     # (x = 1250 - 100 = 1150)
# y: top-315      # (y =  700 -  70 =  630)
# anchor_x: middle
# anchor_y: middle

# -------------
#  Mode Slides
# -------------
slides:
  sl_quidditch_pop_bumper_count:
    widgets:
    - type: text
      font_name: harry-potter
      text: Quidditch Debut
      font_size: 60
      color: score_text_default
      x: left+575
      y: top-280
      anchor_x: middle
      anchor_y: middle
    - type: text
      font_name: harry-potter
      text: (player|var_mc_quidditch_pop_bumper_count) of 'max'
      font_size: 60
      color: score_text_default
      x: left+575
      y: top-350
      anchor_x: middle
      anchor_y: middle
    - widget: widget_main_back_(current_player.house_theme_name)