#config_version=5
mode:           
  start_events: start_mode_field_quidditch_stadium
  stop_events: stop_mode_field_quidditch_stadium
  priority: 300

shot_groups:
  sg_quidditch_statium_qualify:
    shots: sh_pop_left_qualify, sh_pop_right_qualify, sh_pop_bottom_qualify

shots:
  sh_pop_left_qualify:
    enable_events: mode_field_quidditch_stadium_started
    disable_events: sg_quidditch_statium_qualify_hit_complete
    reset_events: mode_field_quidditch_stadium_will_stop
    hit_events: sh_core_pop_left_hit
    profile: sp_quidditch_qualify
    show_tokens:
      led: l_pop_left
      color_name: white
  sh_pop_right_qualify:
    enable_events: mode_field_quidditch_stadium_started
    disable_events: sg_quidditch_statium_qualify_hit_complete
    reset_events: mode_field_quidditch_stadium_will_stop
    hit_events: sh_core_pop_right_hit
    profile: sp_quidditch_qualify
    show_tokens:
      led: l_pop_right
      color_name: white
  sh_pop_bottom_qualify:
    enable_events: mode_field_quidditch_stadium_started
    disable_events: sg_quidditch_statium_qualify_hit_complete
    reset_events: mode_field_quidditch_stadium_will_stop
    hit_events: sh_core_pop_bottom_hit
    profile: sp_quidditch_qualify
    show_tokens:
      led: l_pop_bottom
      color_name: white
  sh_pop_left:
    enable_events: sg_quidditch_statium_qualify_hit_complete
    hit_events: sh_core_pop_left_hit
  sh_pop_right:
    enable_events: sg_quidditch_statium_qualify_hit_complete
    hit_events: sh_core_pop_right_hit
  sh_pop_bottom:
    enable_events: sg_quidditch_statium_qualify_hit_complete
    hit_events: sh_core_pop_bottom_hit
  sh_quidditch_stadium:
    enable_events: sg_quidditch_statium_qualify_hit_complete
    disable_events: mode_field_quidditch_stadium_will_stop
    profile: sp_quidditch_stadium
    advance_events:
      - sg_quidditch_statium_qualify_hit_complete{device.shots.sh_quidditch_stadium.state_name == 'unlit'}
      - quidditch_pop_bumper_count_completed
    hit_events: 
      - sh_pop_left_hit
      - sh_pop_right_hit
      - sh_pop_bottom_hit
    show_tokens:
      led: l_ws2812_shot_quidditch
      color_name: yellow
  sh_quidditch_orbit:
    enable_events: sg_quidditch_statium_qualify_hit_complete
    disable_events: mode_field_quidditch_stadium_will_stop
    profile: sp_quidditch_orbit
    advance_events: sg_quidditch_statium_qualify_hit_complete{device.shots.sh_quidditch_orbit.state_name == 'unlit'}
    hit_events: 
      - sq_shot_orbit_big_left_hit
      - sq_shot_orbit_big_left_alt_hit
    show_tokens:
      led: l_ws2812_shot_forrest
      color_name: yellow
  sh_mis_quidditch:
    profile: sp_mis_quidditch
    persist_enable: true
    advance_events:
      - mode_field_quidditch_stadium_started{device.shots.sh_mis_quidditch.state_name == 'unlit'}
    show_tokens:
      led: l_ws2812_mis_quidditch
      color_name: (current_player.house_theme_led)

shot_profiles:
  sp_quidditch_qualify:
    states:
      - name: lit
        show: flash_normal
      - name: hit
        show: light_on
  sp_quidditch_stadium:
    advance_on_hit: false
    states:
      - name: unlit
        show: light_off
        sync_ms: 500
      - name: lit
        show: flash_normal
        sync_ms: 500
      - name: hit
        show: light_off
        sync_ms: 500
  sp_quidditch_orbit:
    advance_on_hit: true
    states:
      - name: unlit
        show: light_off
        sync_ms: 500
      - name: lit
        show: flash_normal
        sync_ms: 500
      - name: hit
        show: light_off
        sync_ms: 500
  sp_mis_quidditch:
    advance_on_hit: false
    states:
      - name: unlit
        show: light_off
        sync_ms: 500
      - name: lit
        show: flash_normal
        sync_ms: 500
      - name: active
        show: flash_slow
        sync_ms: 500
      - name: completed
        show: on
        sync_ms: 500

accruals:
  lb_quidditch_accrual:
    enable_events: sg_quidditch_statium_qualify_hit_complete
    persist_state: true
    events:
      - quidditch_pop_bumper_count_completed
      - sh_quidditch_orbit_lit_hit
    reset_on_complete: true
    events_when_complete: you_are_a_quidditch_player

counters:
  lb_quidditch_pop_bumper_counter:
    enable_events:
      - sg_quidditch_statium_qualify_hit_complete{device.shots.sh_quidditch_stadium.state_name == 'unlit'}
      - sg_quidditch_statium_qualify_hit_complete{device.shots.sh_quidditch_stadium.state_name == 'lit'}
    disable_events: mode_field_quidditch_stadium_will_stop
    count_events: sh_quidditch_stadium_hit
    count_complete_value: 10
    start_enabled: false
    disable_on_complete: true
    persist_state: true
    events_when_complete: quidditch_pop_bumper_count_completed

show_player:
  sh_pop_left_hit: 
    flash_normal:
      key: pop_left
      action: play
      loops: 0
      show_tokens:
        led: l_pop_left
        color_name: white
  sh_pop_right_hit: 
    flash_normal:
      key: pop_right
      action: play
      loops: 0
      show_tokens:
        led: l_pop_right
        color_name: white
  sh_pop_bottom_hit: 
    flash_normal:
      key: pop_bottom
      action: play
      loops: 0
      show_tokens:
        led: l_pop_bottom
        color_name: white

# Counter -> logic_block_timer (complete all counters within this time)
# Counter ->  control_events:
#              - event: add_five_event
#                action: add
#                value: 5

# # var_mc_ variables are used for mpf-mc for showing on slides.
# variable_player:
#   mode_field_quidditch_stadium_started:
#     var_mc_max_debut_count:
#       int: settings.quidditch_debut_count
#       action: set
#     var_mc_max_return_count:
#       int: settings.quidditch_return_count
#       action: set
#   logicblock_lb_quidditch_debut_count_hit:
#     var_score: 10
#     var_mc_quidditch_debut_count:
#       int: device.counters.lb_quidditch_debut_count.value
#       action: set
#   logicblock_lb_quidditch_return_count_hit:
#     var_score: 100
#     var_mc_quidditch_return_count:
#       int: device.counters.lb_quidditch_return_count.value
#       action: set

# slide_player:
#   logicblock_lb_quidditch_debut_count_hit: 
#     sl_quidditch_debut_count:
#       expire: 0.7s
#   logicblock_lb_quidditch_return_count_hit: 
#     sl_quidditch_return_count:
#       expire: 0.7s


# slides:
#   # Main slide center position is as follows;
#   # x: left+575     # (x = 1250 - 100 = 1150)
#   # y: top-315      # (y =  700 -  70 =  630)
#   # anchor_x: middle
#   # anchor_y: middle
#   sl_quidditch_debut_count:
#     - type: text
#       font_name: harry-potter
#       text: Quidditch Debut
#       font_size: 60
#       color: score_text_default
#       x: left+575
#       y: top-280
#       anchor_x: middle
#       anchor_y: middle
#     - type: text
#       font_name: harry-potter
#       text: (player|var_mc_quidditch_debut_count) of (player|var_mc_max_debut_count)
#       font_size: 60
#       color: score_text_default
#       x: left+575
#       y: top-350
#       anchor_x: middle
#       anchor_y: middle
#     - widget: widget_main_back_(current_player.house_theme_name)
#   sl_quidditch_return_count:
#     - type: text
#       font_name: harry-potter
#       text: Quidditch Return
#       font_size: 60
#       color: score_text_default
#       x: left+575
#       y: top-280
#       anchor_x: middle
#       anchor_y: middle
#     - type: text
#       font_name: harry-potter
#       text: (player|var_mc_quidditch_return_count) of (player|var_mc_max_return_count)
#       font_size: 60
#       color: score_text_default
#       x: left+575
#       y: top-350
#       anchor_x: middle
#       anchor_y: middle
#     - widget: widget_main_back_(current_player.house_theme_name)

