#config_version=5
# ------------------
#  Mode Description
# ------------------
# Step 1 - Shoot all three pop's once to complete the qualify group shot and lit accural shots (quiddich stadium and left orbit shot).
# Step 2 - Make x quidditch stadium shots (pop bumper shots) and one left orbit shot to complete the accural shot.

# Step X - When a ball drains when Spells Light is unlit - Persist counter state_value.
# Step X - When a ball drains when Spells Light is lit - Persist Spells Light shot_state to lit.
# Step X - When a ball drains when Spells Light is active - Reset both Light shots to unlit, reset counter, reset timer and
#          advance state_machine to next level without a bonus.

# ---------------
#  Mode Settings
# ---------------
mode:           
  start_events: start_mode_field_quidditch_stadium
  stop_events: stop_mode_field_quidditch_stadium
  priority: 300

config:
  - field_quidditch_stadium_slides.yaml

# ------------
#  Mode Logic 
# ------------
shot_groups:
  # Step 1 - Qualify group shot
  sg_quidditch_statium_qualify:
    shots: sh_pop_left_qualify, sh_pop_right_qualify, sh_pop_bottom_qualify

shots:
  # Step 1 - Qualify shot
  sh_pop_left_qualify:
    enable_events: mode_field_quidditch_stadium_started
    disable_events: sg_quidditch_statium_qualify_hit_complete
    reset_events: mode_field_quidditch_stadium_will_stop
    hit_events: sh_core_pop_left_hit
    profile: sp_quidditch_qualify
    show_tokens:
      led: l_pop_left
      color_name: white
  # Step 1 - Qualify shot
  sh_pop_right_qualify:
    enable_events: mode_field_quidditch_stadium_started
    disable_events: sg_quidditch_statium_qualify_hit_complete
    reset_events: mode_field_quidditch_stadium_will_stop
    hit_events: sh_core_pop_right_hit
    profile: sp_quidditch_qualify
    show_tokens:
      led: l_pop_right
      color_name: white
  # Step 1 - Qualify shot
  sh_pop_bottom_qualify:
    enable_events: mode_field_quidditch_stadium_started
    disable_events: sg_quidditch_statium_qualify_hit_complete
    reset_events: mode_field_quidditch_stadium_will_stop
    hit_events: sh_core_pop_bottom_hit
    profile: sp_quidditch_qualify
    show_tokens:
      led: l_pop_bottom
      color_name: white
  # Pop bumper shot
  sh_pop_left:
    enable_events: sg_quidditch_statium_qualify_hit_complete
    hit_events: sh_core_pop_left_hit
  # Pop bumper shot
  sh_pop_right:
    enable_events: sg_quidditch_statium_qualify_hit_complete
    hit_events: sh_core_pop_right_hit
  # Pop bumper shot
  sh_pop_bottom:
    enable_events: sg_quidditch_statium_qualify_hit_complete
    hit_events: sh_core_pop_bottom_hit
  # Step 2 - Quidditch Stadium shot (pop bumper shots)
  sh_quidditch_stadium:
    enable_events: sg_quidditch_statium_qualify_hit_complete
    disable_events: mode_field_quidditch_stadium_will_stop
    profile: sp_quidditch_stadium
    advance_events:
      - sg_quidditch_statium_qualify_hit_complete{device.shots.sh_quidditch_stadium.state_name == 'unlit'}
      - quidditch_pop_bumper_count_completed
    hit_events: 
      - sh_pop_left_hit
      - sh_pop_right_hit
      - sh_pop_bottom_hit
    show_tokens:
      led: l_ws2812_shot_quidditch
      color_name: yellow
  # Step 2 - One left orbit shot
  sh_quidditch_orbit:
    enable_events: sg_quidditch_statium_qualify_hit_complete
    disable_events: mode_field_quidditch_stadium_will_stop
    profile: sp_quidditch_orbit
    advance_events: sg_quidditch_statium_qualify_hit_complete{device.shots.sh_quidditch_orbit.state_name == 'unlit'}
    hit_events: 
      # Events from env_orbit and env_orbit_alternative modes
      - sq_shot_orbit_big_left_hit
      - sq_shot_orbit_big_left_alt_hit
    show_tokens:
      led: l_ws2812_shot_forrest
      color_name: yellow
  sh_mis_quidditch:
    profile: sp_mis_quidditch
    persist_enable: true
    advance_events:
      - mode_field_quidditch_stadium_started{device.shots.sh_mis_quidditch.state_name == 'unlit'}
    show_tokens:
      led: l_ws2812_mis_quidditch
      color_name: (current_player.house_theme_led)

shot_profiles:
  sp_quidditch_qualify:
    states:
      - name: lit
        show: flash_normal
        sync_ms: 500
      - name: hit
        show: light_on
        sync_ms: 500
  sp_quidditch_stadium:
    advance_on_hit: false
    states:
      - name: unlit
        show: light_off
        sync_ms: 500
      - name: lit
        show: flash_normal
        sync_ms: 500
      - name: hit
        show: light_off
        sync_ms: 500
  sp_quidditch_orbit:
    advance_on_hit: true
    states:
      - name: unlit
        show: light_off
        sync_ms: 500
      - name: lit
        show: flash_normal
        sync_ms: 500
      - name: hit
        show: light_off
        sync_ms: 500
  sp_mis_quidditch:
    advance_on_hit: false
    states:
      - name: unlit
        show: light_off
        sync_ms: 500
      - name: lit
        show: flash_normal
        sync_ms: 500
      - name: active
        show: flash_slow
        sync_ms: 500
      - name: completed
        show: on
        sync_ms: 500

accruals:
  # Step 2 - Accural shot to complete
  lb_quidditch_accrual:
    enable_events: sg_quidditch_statium_qualify_hit_complete
    persist_state: true
    events:
      - quidditch_pop_bumper_count_completed
      - sh_quidditch_orbit_lit_hit
    reset_on_complete: true
    events_when_complete: you_are_a_quidditch_player

counters:
  # Step 2 - Make x Quidditch Stadium shots (pop bumper shots)
  lb_quidditch_pop_bumper_counter:
    enable_events:
      - sg_quidditch_statium_qualify_hit_complete{device.shots.sh_quidditch_stadium.state_name == 'unlit'}
      - sg_quidditch_statium_qualify_hit_complete{device.shots.sh_quidditch_stadium.state_name == 'lit'}
    disable_events: mode_field_quidditch_stadium_will_stop
    count_events: sh_quidditch_stadium_hit
    count_complete_value: 10
    start_enabled: false
    disable_on_complete: true
    persist_state: true
    events_when_complete: quidditch_pop_bumper_count_completed
    
# Counter -> logic_block_timer (complete all counters within this time)
# Counter ->  control_events:
#              - event: add_five_event
#                action: add
#                value: 5

# ----------------
#  Config Players 
# ----------------
show_player:
  sh_pop_left_hit: 
    flash_normal:
      key: pop_left
      action: play
      loops: 0
      show_tokens:
        led: l_pop_left
        color_name: white
  sh_pop_right_hit: 
    flash_normal:
      key: pop_right
      action: play
      loops: 0
      show_tokens:
        led: l_pop_right
        color_name: white
  sh_pop_bottom_hit: 
    flash_normal:
      key: pop_bottom
      action: play
      loops: 0
      show_tokens:
        led: l_pop_bottom
        color_name: white

sound_player:
  sg_quidditch_statium_qualify_hit:
    pop_bumper_pool:
      action: play
  sh_quidditch_stadium_hit:
    pop_bumper_pool:
      action: play
  sh_quidditch_orbit_lit_hit:
    mysterious_03:
      action: play

# var_mc_ variables are used for mpf-mc for showing on slides.
variable_player:
  logicblock_lb_quidditch_pop_bumper_counter_hit:
    var_score: 10
    var_mc_quidditch_pop_bumper_count:
      int: device.counters.lb_quidditch_pop_bumper_counter.value
      action: set

slide_player:
  logicblock_lb_quidditch_pop_bumper_counter_hit: 
    sl_quidditch_pop_bumper_count:
      expire: 0.7s