#config_version=6
config:
  - config_assets.yaml
  - config_credits.yaml
  - config_mechanisms.yaml
  - config_settings.yaml
  - hardware_opp_coils.yaml
  - hardware_opp_lights_neo0.yaml
  - hardware_opp_lights_neo1.yaml
  - hardware_opp_lights_neo3.yaml
  - hardware_opp_lights_spots.yaml
  - hardware_opp_servos.yaml
  - hardware_opp_switches.yaml

hardware:
  platform: opp, virtual
  # OPP board revision
  driverboards: gen2
  lights: opp, drivers

opp:
  ports: COM3, COM4, COM5, COM6
  debug: false
    
virtual_platform_start_active_switches:
  - s_trough_1
  - s_trough_2
  - s_trough_3
  - s_trough_4
  - s_trough_5

machine:
  balls_installed: 5
  min_balls: 5

game:
  balls_per_game: settings.balls_per_game
  max_players: 4
  add_player_switch_tag: add_player
  
named_colors:
  # Original colors for the four houses
  gryffindor_red: [127, 9, 9]         # 7F0909
  gryffindor_gold: [255, 197, 0]      # FFC500
  hufflepuff_yellow: [238, 225, 23]   # EEE117 
  hufflepuff_black: [0, 0, 0]         # 000000
  ravenclaw_blue: [0, 10, 144]        # 000A90
  ravenclaw_bronze: [148, 107, 45]    # 946B2D
  slytherin_green: [13, 98, 23]       # 0D6217
  slytherin_silver: [170, 170, 170]   # AAAAAA
  # Custom colors used
  flames: [232, 84, 18]
  score_text_default: [255, 255, 255] # White  
  gryffindor_led: [255, 0, 0]         # Red
  hufflepuff_led: [255, 255, 0]       # Yellow 
  ravenclaw_led: [0, 0, 255]          # Blue
  slytherin_led: [0, 153, 76]         # Green

modes:
  #|==========================|#
  #| NOTE | Envoirement modes |#
  #|==========================|# 
  - service
  - credits
  - env_house_theme_selection
  - env_subway
  - skill_shots

  #|====================|#
  #| NOTE | Logic modes |#
  #|====================|# 
  - base
  - global

  #|====================|#
  #| NOTE | Field modes |#
  #|====================|# 
  - field_orbits_option1
  - field_orbits_option2
  - field_orbits_option3
  - field_chamber_of_secrets
  - field_clock_tower
  - field_diagon_alley
  - field_quidditch_stadium
  - field_hogwarts_castle_level1
  - field_ministry_of_magic
  - field_house_cup
  - field_platform_nine_three_quarters
  - field_spells_ramp
  - field_deathly_hallows

  #|======================|#
  #| NOTE | Mission modes |#
  #|======================|# 
  - mission_quidditch
  - mission_deathly_hallows
  - mission_hagrids_place
  #- mission_spells
  #- house_gryffindor
  #- house_hufflepuf
  #- house_ravenclaw
  #- house_slydirin