#config_version=5

# HARDWARE MECHANISM LIMITATIONS
# div_tower_entry (div 1) CAN ONLY BE DEACTIVATED WHEN div_tower_pensieve (div 2) IS DEACTIVE
# div_tower_pensieve (div 2) CAN ONLY BE ACTIVATED WHEN div_tower_entry (div 1) IS ENABLED AND ACTIVE AND WHEN bd_tower HAS A BALL (s_tower)
# div_tower_pensieve (div 2) CAN ONLY BE DEACTIVATED WHEN div_tower_entry (div 1) IS ENABLED AND ACTIVE AND WHEN bd_tower HAS NO BALL (s_tower)

flippers:
  left_flipper:
    main_coil: c_fl_left_power
    hold_coil: c_fl_left_hold
    activation_switch: s_fl_left_a
    enable_events: ball_starting, normal_lower_flippers_on
    disable_events: ball_ending, service_mode_entered, flippers_off, weak_lower_flippers_on, flip_lower_flippers_on
  right_flipper:
    main_coil: c_fl_right_power
    hold_coil: c_fl_right_hold
    activation_switch: s_fl_right_a
    enable_events: ball_starting, normal_lower_flippers_on
    disable_events: ball_ending, service_mode_entered, flippers_off, weak_lower_flippers_on, flip_lower_flippers_on
  left_top_flipper:
    main_coil: c_fl_top_left_power
    hold_coil: c_fl_top_left_hold
    activation_switch: s_fl_left_b
    enable_events: enable_left_top_flipper
    disable_events: disable_left_top_flipper, service_mode_entered
  right_top_flipper:
    main_coil: c_fl_top_right_power
    hold_coil: c_fl_top_right_hold
    activation_switch: s_fl_right_b
    enable_events: enable_right_top_flipper
    disable_events: disable_right_top_flipper, service_mode_entered
  # left_flipper_weak:
  #   main_coil: c_fl_left_power
  #   hold_coil: c_fl_left_hold
  #   main_coil_overwrite:
  #     pulse_power: 0.3
  #   activation_switch: s_fl_left_a
  #   enable_events: weak_flippers_on
  #   disable_events: ball_ending, service_mode_entered, flippers_off, flippers_on, flip_flippers_on
  # right_flipper_weak:
  #   main_coil: c_fl_right_power
  #   hold_coil: c_fl_right_hold
  #   main_coil_overwrite:
  #     pulse_power: 0.3
  #   activation_switch: s_fl_right_a
  #   enable_events: weak_flippers_on
  #   disable_events: ball_ending, service_mode_entered, flippers_off, flippers_on, flip_flippers_on
  # left_flipper_flip:
  #   main_coil: c_fl_left_power
  #   hold_coil: c_fl_left_hold
  #   activation_switch: s_fl_right_a
  #   enable_events: flip_flippers_on
  #   disable_events: ball_ending, service_mode_entered, flippers_off, flippers_on, weak_flippers_on
  # right_flipper_flip:
  #   main_coil: c_fl_right_power
  #   hold_coil: c_fl_right_hold
  #   activation_switch: s_fl_left_a
  #   enable_events: flip_flippers_on
  #   disable_events: ball_ending, service_mode_entered, flippers_off, flippers_on, weak_flippers_on

ball_devices:
  bd_plunger:
    ball_switches: s_plunger_lane
    eject_coil: c_auto_plunger
    mechanical_eject: true
    eject_timeouts: 3s
    debug: false
  bd_trough:
    ball_switches: s_trough_1, s_trough_2, s_trough_3, s_trough_4, s_trough_5
    eject_coil: c_trough_release
    eject_targets: bd_plunger
    tags: home, trough
    debug: false
  bd_drain:
    ball_switches: s_drain
    eject_coil: c_drain_eject
    eject_targets: bd_trough
    tags: drain
    debug: false
  bd_subway_vuk_left_buffer:
    ball_switches: s_subway_vuk_left_buffer_1, s_subway_vuk_left_buffer_2
    # Used a dummy coil and the ball_device events to position the servo (see servo config in hardware_pololu.yaml) instead of the event_ejector class.
    eject_coil: c_subway_vuk_left_buffer
    eject_targets: bd_subway_vuk_left
    confirm_eject_type: target
  bd_subway_vuk_left_buffer_chamber:
    ball_switches: s_subway_vuk_left_buffer_chamber
    # Used a dummy coil and the ball_device events to position the servo (see servo config in hardware_pololu.yaml) instead of the event_ejector class.
    eject_coil: c_subway_vuk_left_buffer_chamber
    eject_targets: bd_subway_vuk_left
    confirm_eject_type: target
  bd_subway_vuk_right_buffer:
    ball_switches: s_subway_vuk_right_buffer_1, s_subway_vuk_right_buffer_2
    # Used a dummy coil and the ball_device events to position the servo (see servo config in hardware_pololu.yaml) instead of the event_ejector class.
    eject_coil: c_subway_vuk_right_buffer
    eject_targets: bd_subway_vuk_right
    confirm_eject_type: target
  bd_subway_vuk_selector:
    ball_switches: s_subway_vuk_selector
    # Used a dummy coil and the ball_device events to transistion the state machine (mode env_subway) instead of the event_ejector class.
    eject_coil: c_subway_vuk_selector
    confirm_eject_type: target  
  bd_subway_vuk_left:
    ball_switches: s_subway_vuk_left
    eject_coil: c_subway_vuk_left
    eject_targets: playfield
    confirm_eject_type: target
  bd_subway_vuk_right:
    ball_switches: s_subway_vuk_right
    eject_coil: c_subway_vuk_right
    eject_targets: playfield
    confirm_eject_type: target
  bd_diagon_alley_vuk:
    ball_switches: s_vuk_top
    eject_coil: c_vuk_top
    eject_targets: playfield
    confirm_eject_type: target
  bd_ministry_vuk:
    ball_switches: s_vuk_bottom
    eject_coil: c_vuk_bottom
    eject_targets: playfield
    confirm_eject_type: target
  bd_forest_kicker:
    ball_switches: s_forest_kicker
    eject_coil: c_forest_kicker
    eject_targets: playfield
    confirm_eject_type: target
  bd_clock_tower:
    ball_switches: s_tower
    # Used a dummy coil
    eject_coil: c_clock_tower
    eject_targets: playfield
    confirm_eject_type: target

# Diverters without an "activate_events" event is activated immediately after enabling the diverter.
diverters:
  div_hagrid_place:
    enable_events: mode_mission_hagrids_place_started
    disable_events: mode_mission_hagrids_place_stopped
    activation_switches: s_spells_ramp_entry
    deactivation_switches: s_hagrid
    activation_coil: c_div_hagrid
    activation_time: 3s
    cool_down_time: 10s
    debug: false
  div_tower_entry:
    enable_events: enable_div_tower_entry
    disable_events: disable_div_tower_entry{device.diverters.div_tower_entry.active==False}
    activation_coil: c_div_tower_1
    activate_events: activate_div_tower_entry
    deactivate_events: deactivate_div_tower_entry{device.diverters.div_tower_pensieve.active==False}
    debug: false
  div_tower_pensieve:
    enable_events: enable_div_tower_pensieve
    disable_events: disable_div_tower_pensieve{device.diverters.div_tower_pensieve.active==False}
    activation_coil: c_div_tower_2
    activate_events: activate_div_tower_pensieve{device.diverters.div_tower_entry.active==True}
    deactivate_events: deactivate_div_tower_pensieve{device.diverters.div_tower_entry.active==True}
    debug: false
  div_castle:
    enable_events: enable_div_castle
    disable_events: disable_div_castle
    activation_coil: c_div_castle
    activate_events: activate_div_castle
    deactivate_events: deactivate_div_castle
    debug: false
  div_forest:
    enable_events: enable_div_forest
    disable_events: disable_div_forest
    activation_coil: c_div_forest
    activate_events: activate_div_forest
    deactivate_events: deactivate_div_forest
    debug: false
  div_castle_door:
    enable_events: ball_started
    disable_events: ball_ended
    activation_coil: c_div_castle_door
    activate_events: test_div_castle_door_active
    deactivate_events: test_div_castle_door_deactive
    debug: true  
        
drop_targets:
  dt_hogwarts_castle:
    switch: s_castle_door
  dt_gringotts_bank:
    switch: s_drop_1er
  dt_ministry_of_magic_1:
    switch: s_drop_3er_1
  dt_ministry_of_magic_2:
    switch: s_drop_3er_2
  dt_ministry_of_magic_3:
    switch: s_drop_3er_3

drop_target_banks:
  dtb_hogwarts_castle:
    drop_targets: dt_hogwarts_castle
    reset_coils: c_div_castle_door
    reset_events: machine_reset_phase_3, ball_starting, reset_dropbank_hogwarts_castle
  dtb_gringotts_bank:
    drop_targets: dt_gringotts_bank
    reset_coils: c_drop_1er
    reset_events: machine_reset_phase_3, ball_starting, reset_dropbank_gringotts_bank
  dtb_ministry_of_magic:
    drop_targets: dt_ministry_of_magic_1, dt_ministry_of_magic_2, dt_ministry_of_magic_3
    reset_coils: c_drop_3er
    reset_events: machine_reset_phase_3, ball_starting, reset_dropbank_ministry_of_magic

magnets:
  mag_hogwarts_castle:
    magnet_coil: c_magnet_hogwarts_castle
    grab_time: 1.5s # Default is 1.5s
    grab_ball_events: mag_hogwarts_castle_grab_ball
    fling_ball_events: mag_hogwarts_castle_fling_ball
    fling_drop_time: 250ms # Default: 250ms
    fling_regrab_time: 50ms # Default: 50ms
    release_ball_events: mag_all_release, mag_hogwarts_castle_release
  mag_playfield:
    magnet_coil: c_magnet_playfield
    grab_time: 1.5s # Default is 1.5s
    grab_ball_events: mag_playfield_grab_ball
    fling_ball_events: mag_playfield_fling_ball
    fling_drop_time: 250ms # Default: 250ms
    fling_regrab_time: 50ms # Default: 50ms
    release_ball_events: mag_all_release, mag_playfield_release
  mag_clock_tower:
    magnet_coil: c_magnet_clock_tower
    grab_ball_events: mag_clock_tower_grab_ball
    grab_switch:
    grab_time: 1.5s # Default is 1.5s
    fling_ball_events: mag_clock_tower_fling_ball
    fling_drop_time: 250ms # Default: 250ms
    fling_regrab_time: 50ms # Default: 50ms
    release_ball_events: mag_all_release, mag_clock_tower_release

autofire_coils:
  left_slingshot:
    coil: c_sling_left
    switch: s_sling_left
    enable_events: ball_starting, slingshots_on
    disable_events: ball_ending, service_mode_entered, slingshots_off
  right_slingshot:
    coil: c_sling_right
    switch: s_sling_right
    enable_events: ball_starting, slingshots_on
    disable_events: ball_ending, service_mode_entered, slingshots_off
  left_bumper:
    switch: s_pop_left
    coil: c_pop_left
    enable_events: ball_starting, bumpers_on
    disable_events: ball_ending, service_mode_entered, bumpers_off
    tags: bumper
  right_bumper:
    switch: s_pop_right
    coil: c_pop_right
    enable_events: ball_starting, bumpers_on
    disable_events: ball_ending, service_mode_entered, bumpers_off
    tags: bumper
  bottom_bumper:
    switch: s_pop_bottom
    coil: c_pop_bottom
    enable_events: ball_starting, bumpers_on
    disable_events: ball_ending, service_mode_entered, bumpers_off
    tags: bumper

playfields:
  playfield:
    default_source_device: bd_plunger
    # During development ball search off.
    enable_ball_search: false
    tags: default
