#config_version=5
opp:
  ports: /dev/ttyOPP-0, /dev/ttyOPP-1, /dev/ttyOPP-2, /dev/ttyOPP-3, /dev/ttyOPP-4
  chains:
    0: /dev/ttyOPP-0
    1: /dev/ttyOPP-1
    2: /dev/ttyOPP-2
    3: /dev/ttyOPP-3
    4: /dev/ttyOPP-4
  debug: true

#|====================================|#
#| - COIL SAFETY - DO NOT BURN THEM - |#
#|====================================|#
#| Use "allow_enable" or "default_bold_power" when coils needs to be on for a longer period of time. This will prevent them from burning out!
#| Using "allow_enable: true" instead of default_pulse_power for flippers because these are dual-wounded coil so the power is controlled through coil wires.
#| Using "default_hold_power" for all other coils that need to be on for a longer period time and set the desired power from 0 to 1 where 1 is 100%.

# TODO
# Playfield active switches (Not by shots, handled internaly)

coils:
  # OPP CHAIN 0 BOARD 0
  c_fl_left_power:
    platform: opp
    number: 0-0-8
    default_pulse_ms: 45
  c_fl_left_hold:
    platform: opp
    number: 0-0-9
    allow_enable: true
  c_fl_right_power:
    platform: opp
    number: 0-0-10
    default_pulse_ms: 45
  c_fl_right_hold:
    platform: opp
    number: 0-0-11
    allow_enable: true
  c_drain_eject:
    platform: opp
    number: 0-0-12
    default_pulse_ms: 15
  c_auto_plunger:
    platform: opp
    number: 0-0-13
    default_pulse_ms: 30
  c_sling_right:
    platform: opp
    number: 0-0-14
    default_pulse_ms: 5
  c_sling_left:
    platform: opp
    number: 0-0-15
    default_pulse_ms: 5
  # OPP CHAIN 2 BOARD 0
  c_fl_top_right_power:
    platform: opp
    number: 2-0-8
    default_pulse_ms: 25
  c_fl_top_right_hold:
    platform: opp
    number: 2-0-9
    default_pulse_ms: 10
    allow_enable: true  
  c_drop_3er:
    platform: opp
    number: 2-0-10
    default_pulse_ms: 25
  c_trough_release:
    platform: opp
    number: 2-0-11
    default_pulse_ms: 15
  c_pop_right:
    platform: opp
    number: 2-0-12
    default_pulse_ms: 15
  c_vuk_bottom:
    platform: opp
    number: 2-0-13
    default_pulse_ms: 30
  c_pop_bottom:
    platform: opp
    number: 2-0-14
    default_pulse_ms: 15
  c_pop_left:
    platform: opp
    number: 2-0-15
    default_pulse_ms: 15
  # OPP CHAIN 3 BOARD 0
  c_magnet_castle:
    platform: opp
    number: 3-0-8
    default_pulse_ms: 10
    default_hold_power: 0.1
  c_drop_1er:
    platform: opp
    number: 3-0-9
    default_pulse_ms: 25
  c_fl_top_left_power:
    platform: opp
    number: 3-0-10
    default_pulse_ms: 25
  c_fl_top_left_hold:
    platform: opp
    number: 3-0-11
    default_pulse_ms: 10
    allow_enable: true
  c_div_castle_door:
    platform: opp
    number: 3-0-12
    default_pulse_ms: 55
    default_hold_power: 0.2
  c_vuk_top:
    platform: opp
    number: 3-0-13
    default_pulse_ms: 20
  c_magnet_tower:
    platform: opp
    number: 3-0-14
    default_pulse_ms: 10
    default_hold_power: 0.1
  c_subway_vuk_right:
    platform: opp
    number: 3-0-15
    default_pulse_ms: 125
  # OPP CHAIN 4 BOARD 0
  c_subway_vuk_left:
    platform: opp
    number: 4-0-8
    default_pulse_ms: 100
  c_div_forest:
    platform: opp
    number: 4-0-9
    default_pulse_ms: 4
    default_hold_power: 0.1
  c_div_castle:
    platform: opp
    number: 4-0-10
    default_pulse_ms: 4
    default_hold_power: 0.1
  c_div_hagrid:
    platform: opp
    number: 4-0-11
    default_pulse_ms: 25
    default_hold_power: 0.1
  c_magnet_main:
    platform: opp
    number: 4-0-12
    default_pulse_ms: 10
    default_hold_power: 0.1
  c_div_tower_2:
    platform: opp
    number: 4-0-13
    default_pulse_ms: 4
    default_hold_power: 0.1
  c_div_tower_1:
    platform: opp
    number: 4-0-14
    default_pulse_ms: 4
    default_hold_power: 0.1
  c_forest_kicker:
    platform: opp
    number: 4-0-15
    default_pulse_ms: 100
  # Dummy coils for ball_devices with a servo.
  c_subway_vuk_left_buffer:
    platform: virtual
    number:
  c_subway_vuk_left_buffer_chamber:
    platform: virtual
    number:
  c_subway_vuk_right_buffer:
    platform: virtual
    number:
  c_subway_vuk_selector:
    platform: virtual
    number:
  c_clock_tower:
    platform: virtual
    number:

switches:
  # OPP CHAIN 0 BOARD 0
  s_drain:
    platform: opp
    number: 0-0-0
  s_trough_1:
    platform: opp
    number: 0-0-1
  s_trough_2:
    platform: opp
    number: 0-0-2
  s_trough_3:
    platform: opp
    number: 0-0-3
  s_trough_4:
    platform: opp
    number: 0-0-4
  s_plunger_lane:
    platform: opp
    number: 0-0-5
  s_trough_5:
    platform: opp
    number: 0-0-6
  s_lane_fl_right:
    platform: opp
    number: 0-0-8
    tags: playfield_active
  s_lane_dr_right:
    platform: opp
    number: 0-0-9
    tags: playfield_active
  s_lane_fl_left:
    platform: opp
    number: 0-0-10
    tags: playfield_active
  s_lane_dr_left:
    platform: opp
    number: 0-0-11
    tags: playfield_active
  s_fl_left_a:
    platform: opp
    number: 0-0-16
    tags: flipper_left
  s_fl_right_a:
    platform: opp
    number: 0-0-18
    tags: flipper_right
  s_sling_right:
    platform: opp
    number: 0-0-26
  s_sling_left:
    platform: opp
    number: 0-0-27
  # OPP CHAIN 2 BOARD 0
  s_tar_nimbus:
    platform: opp
    number: 2-0-0
    tags: playfield_active
  s_tar_light_diagon_alley:
    platform: opp
    number: 2-0-1
  s_tar_sword:
    platform: opp
    number: 2-0-2
  s_tar_platform:
    platform: opp
    number: 2-0-3
  #s_spinner:
  #  platform: opp
  #  number: 0-2-20
  s_drop_3er_1:
    platform: opp
    number: 2-0-8
    type: 'NC'
  s_drop_3er_3:
    platform: opp
    number: 2-0-9
    type: 'NC'
  s_drop_3er_2:
    platform: opp
    number: 2-0-10
    type: 'NC'
  s_vuk_bottom:
    platform: opp
    number: 2-0-11
  s_left_wire_ramp:
    platform: opp
    number: 2-0-12
  s_right_wire_ramp_small:
    platform: opp
    number: 2-0-14
  s_hagrid:
    platform: opp
    number: 2-0-15
  s_fl_right_b:
    platform: opp
    number: 2-0-16
  s_pop_right:
    platform: opp
    number: 2-0-24
  s_pop_bottom:
    platform: opp
    number: 2-0-26
  s_pop_left:
    platform: opp
    number: 2-0-27
  # OPP CHAIN 3 BOARD 0
  s_subway_vuk_selector:
    platform: opp
    number: 3-0-0
  s_subway_vuk_right_buffer_2:
    platform: opp
    number: 3-0-1 
  s_subway_vuk_right_buffer_1:
    platform: opp
    number: 3-0-2
  s_subway_vuk_right:
    platform: opp
    number: 3-0-3
  s_subway_vuk_left_buffer_1:
    platform: opp
    number: 3-0-4
  s_subway_vuk_left_buffer_2:
    platform: opp
    number: 3-0-5
  s_subway_vuk_left_buffer_chamber:
    platform: opp
    number: 3-0-6
  s_subway_vuk_left:
    platform: opp
    number: 3-0-7
  s_tar_c_left:
    platform: opp
    number: 3-0-8
    tags: playfield_active
  s_captive_ball:
    platform: opp
    number: 3-0-9
  s_tar_wand:
    platform: opp
    number: 3-0-10
  s_tar_stone:
    platform: opp
    number: 3-0-11
  s_tar_cloak:
    platform: opp
    number: 3-0-12
  s_drop_1er:
    platform: opp
    number: 3-0-13
  s_spells_ramp_entry:
    platform: opp
    number: 3-0-14
  s_tower_ramp_entry:
    platform: opp
    number: 3-0-15
  s_fl_left_b:
    platform: opp
    number: 3-0-18
  s_vuk_top:
    platform: opp
    number: 3-0-25
  s_tower:
    platform: opp
    number: 3-0-26
  # OPP CHAIN 4 BOARD 0
  s_diagon_alley:
    platform: opp
    number: 4-0-2
    tags: playfield_active
  s_div_castle:
    platform: opp
    number: 4-0-3
    tags: playfield_active
  s_right_wire_ramp_big_1:
    platform: opp
    number: 4-0-4
  s_castle_door:
    platform: opp
    number: 4-0-5
  s_right_wire_ramp_big_2:
    platform: opp
    number: 4-0-6
  s_tar_c_right:
    platform: opp
    number: 4-0-7
    tags: playfield_active
  s_forest_kicker:
    platform: opp
    number: 4-0-17
  s_orbit_right:
    platform: opp
    number: 4-0-18
  s_orbit_left:
    platform: opp
    number: 4-0-27
    
lights:
  # OPP CHAIN 1 BOARD 0
  l_pop_left:
    platform: opp
    number: 1-0-16
    subtype: incand
    debug: true
  l_pop_right:
    platform: opp
    number: 1-0-17
    subtype: incand
    debug: true
  l_pop_bottom:
    platform: opp
    number: 1-0-18
    subtype: incand
    debug: true
  l_flip_lane_left:
    platform: opp
    number: 1-0-19
    subtype: incand
    debug: true
  l_flip_lane_right:
    platform: opp
    number: 1-0-20
    subtype: incand
    debug: true
  l_sling_left:
    platform: opp
    number: 1-0-21
    subtype: incand
    debug: true
  l_sling_right:
    platform: opp
    number: 1-0-22
    subtype: incand
    debug: true
  l_spot_sling_left:
    platform: opp
    number: 1-0-23
    subtype: incand
    debug: true
  l_spot_sling_right:
    platform: opp
    number: 1-0-24
    subtype: incand
    debug: true
  l_side_left:
    platform: opp
    number: 1-0-25
    subtype: incand
    debug: true
  l_side_right:
    platform: opp
    number: 1-0-26
    subtype: incand
    debug: true
  l_side_drain:
    platform: opp
    number: 1-0-27
    subtype: incand
    debug: true
  l_side_top_left:
    platform: opp
    number: 1-0-28
    subtype: incand
    debug: true
  l_side_top_right:
    platform: opp
    number: 1-0-29
    subtype: incand
    debug: true