#config_version=6
#|====================================|#
#| - COIL SAFETY - DO NOT BURN THEM - |#
#|====================================|#
#| Use "allow_enable" or "default_hold_power" when coils needs to be on for a longer period of time. This will prevent them from burning out!
#| Using "allow_enable: true" instead of default_pulse_power for flippers because these are dual-wounded coil so the power is controlled through coil wires.
#| Using "default_hold_power" for all other coils that need to be on for a longer period time and set the desired power from 0 to 1 where 1 is 100%.
#|========================================|#
#| - MAGNET SAFETY - DO NOT ENABLE THEM - |#
#|========================================|#
#| NEVER full enable magnets, use short pulses + PWM instead!
#| Using "default_hold_power" for magnets that need to be on for a longer period time and set the desired power from 0 to 1 where 1 is 100%. Do not use a higher value then 30% at max instead!

#TODO
# Playfield active switches (Not by shots, handled internaly)

coils:
  # Flipper main left
  c_fl_left_power:
    platform: opp
    number: 0-0-6
    default_pulse_ms: 10
  c_fl_left_hold:
    platform: opp
    number: 0-0-5
    allow_enable: true
  # Flipper main right
  c_fl_right_power:
    platform: opp
    number: 0-0-10
    default_pulse_ms: 10
  c_fl_right_hold:
    platform: opp
    number: 0-0-11
    allow_enable: true
  # Flipper top left
  c_fl_top_left_power:
    platform: opp
    number: 0-0-8
    default_pulse_ms: 10
  c_fl_top_left_hold:
    platform: opp
    number: 0-0-9
    allow_enable: true
  # Flipper top right
  c_fl_top_right_power:
    platform: opp
    number: 0-0-15
    default_pulse_ms: 10
  c_fl_top_right_hold:
    platform: opp
    number: 0-0-7
    allow_enable: true
  # Sling shots
  c_sling_left:
    platform: opp
    number: 0-0-13
    default_pulse_ms: 10
  c_sling_right:
    platform: opp
    number: 0-0-14
    default_pulse_ms: 10
  # Pop bumpers
  c_pop_right:
    platform: opp
    number: 1-0-3
    default_pulse_ms: 10
  c_pop_bottom:
    platform: opp
    number: 1-0-2
    default_pulse_ms: 10
  c_pop_left:
    platform: opp
    number: 1-0-1
    default_pulse_ms: 10
  # Drop targets
  c_drop1_castle_door:
    platform: opp
    number: 0-0-0
    default_pulse_ms: 10
  c_drop1_gringotts:
    platform: opp
    number: 3-0-5
    default_pulse_ms: 10
  c_drop3_ministry:
    platform: opp
    number: 3-0-4
    default_pulse_ms: 10
  # VUK's
  c_subway_vuk_right:
    platform: opp
    number: 1-0-6
    default_pulse_ms: 10
  c_subway_vuk_left:
    platform: opp
    number: 1-0-5
    default_pulse_ms: 10
  c_vuk_forrest:
    platform: opp
    number: 0-0-12
    default_pulse_ms: 10
  c_vuk_ministry:
    platform: opp
    number: 3-0-3
    default_pulse_ms: 10
  c_vuk_diagon_alley:
    platform: opp
    number: 3-0-2
    default_pulse_ms: 10
  # Diverters
  c_div_orbit_forrest:
    platform: opp
    number: 1-0-0
    default_pulse_ms: 10
    default_hold_power: 0.1
  c_div_orbit_long:
    platform: opp
    number: 0-0-2
    default_pulse_ms: 10
    default_hold_power: 0.1
  c_div_spell_ramp_hagrid:
    platform: opp
    number: 1-0-7
    default_pulse_ms: 10
    default_hold_power: 0.1
  c_div_tower_exit_normal:
    platform: opp
    number: 0-0-4
    default_pulse_ms: 10
    default_hold_power: 0.1
  c_div_tower_exit_pensieve:
    platform: opp
    number: 0-0-3
    default_pulse_ms: 10
    default_hold_power: 0.1
  # Magnets - NEVER full enable magnets, see explanation above.
  c_magnet_clock_tower:
    platform: opp
    number: 1-0-4
    default_pulse_ms: 10
    default_hold_power: 0.1
  # Drain, Trough, Plunger
  c_drain_eject:
    platform: opp
    number: 3-0-0
    default_pulse_ms: 10
  c_trough_release:
    platform: opp
    number: 3-0-7
    default_pulse_ms: 10
  c_auto_plunger:
    platform: opp
    number: 3-0-6
    default_pulse_ms: 10
  # GI Spots
  c_gi_spots:
    platform: opp
    number: 3-0-1
    allow_enable: true
  # Dummy coils for ball_devices with a servo.
  c_subway_vuk_left_buffer:
    platform: virtual
    number:
  c_subway_vuk_left_buffer_chamber:
    platform: virtual
    number:
  c_subway_vuk_right_buffer:
    platform: virtual
    number:
  c_subway_vuk_selector:
    platform: virtual
    number:
  c_clock_tower:
    platform: virtual
    number: