#config_version=6
switches:
  # Cabinet switches
  s_start_button:
    platform: opp
    type: NC
    number: 8-0-16
    debounce: normal
    ignore_window_ms: 500
    tags: start
  s_coin:
    platform: opp
    number: 8-0-17
  s_service_door:
    platform: opp
    number: 8-0-18
    tags: service_door_open, power_off
  s_service_enter:
    platform: opp
    number: 8-0-19
    tags: service_enter
  s_service_esc:
    platform: opp
    number: 8-0-20
    tags: service_esc
  s_service_up:
    platform: opp
    number: 8-0-21
    tags: service_up
  s_service_down:
    platform: opp
    number: 8-0-22
    tags: service_down
  # Flipper buttons
  s_fl_left_a:
    platform: opp
    number: 1-0-31
    tags: flipper_left
  s_fl_right_a:
    platform: virtual
    number: 
    tags: flipper_right
  # Drain, Trough, Plunger
  s_drain:
    platform: opp
    number: 3-0-23
  s_trough_1:
    platform: opp
    number: 3-0-21
  s_trough_2:
    platform: opp
    number: 3-0-22
  s_trough_3:
    platform: opp
    number: 3-0-17
  s_trough_4:
    platform: opp
    number: 3-0-26
  s_trough_5:
    platform: opp
    number: 3-0-25
  s_plunger_lane:
    platform: opp
    number: 3-0-19
  # Lanes
  s_lane_dr_left:
    platform: opp
    number: 3-0-2
    tags: playfield_active
  s_lane_dr_right:
    platform: opp
    number: 3-0-20
    tags: playfield_active
  s_lane_fl_left:
    platform: opp
    number: 3-0-18
    tags: playfield_active
  s_lane_fl_right:
    platform: opp
    number: 3-0-24
    tags: playfield_active
  # Sling shots
  s_sling_right:
    platform: opp
    number: 0-0-3
  s_sling_left:
    platform: opp
    number: 0-0-11
  # Pop bumpers
  s_pop_right:
    platform: opp
    number: 1-0-18
  s_pop_bottom:
    platform: opp
    number: 1-0-17
  s_pop_left:
    platform: opp
    number: 1-0-16
  # Targets
  s_tar_light_diagon_alley:
    platform: opp
    number: 1-0-19
  s_tar_nimbus:
    platform: opp
    number: 0-0-10
    tags: playfield_active
  s_tar_sword:
    platform: opp
    number: 0-0-27
  s_tar_platform:
    platform: opp
    number: 0-0-25
  s_tar_wand:
    platform: opp
    number: 3-0-10
  s_tar_stone:
    platform: opp
    number: 3-0-8
  s_tar_cloak:
    platform: opp
    number: 3-0-3
  s_tar_castle_left:
    platform: opp
    number: 3-0-9
    tags: playfield_active
  s_tar_castle_right:
    platform: opp
    number: 3-0-11
    tags: playfield_active
  s_captive_ball:
    platform: opp
    number: 3-0-29
  # Drop targets
  s_drop1_castle_door:
    platform: opp
    number: 0-0-9
  s_drop1_gringotts:
    platform: opp
    number: 3-0-30
  s_drop3_ministry_1:
    platform: opp
    number: 3-0-27
    type: 'NC'
  s_drop3_ministry_2:
    platform: opp
    number: 3-0-16
    type: 'NC'
  s_drop3_ministry_3:
    platform: opp
    number: 3-0-1
    type: 'NC'
  # VUK's
  s_vuk_diagon_alley:
    platform: opp
    number: 0-0-18
  s_vuk_forrest:
    platform: opp
    number: 1-0-21
  s_vuk_ministry:
    platform: opp
    number: 3-0-31
  # Orbits & Spinners
  s_orbit_right:
    platform: virtual
    number: 
  s_orbit_left:
    platform: opp
    number: 1-0-23
  s_spinner_diagon_alley:
    platform: opp
    number: 0-0-19
    tags: playfield_active
  s_spinner_short_orbit:
    platform: opp
    number: 0-0-17
    tags: playfield_active
  s_spinner_right_orbit:
    platform: opp
    number: 3-0-28
    tags: playfield_active
  # Ramps & Wire ramps
  s_spells_ramp_entry:
    platform: opp
    number: 1-0-1
  s_spells_ramp_wire_exit:
    platform: opp
    number: 0-0-16
  s_spells_ramp_hagrid_exit:
    platform: opp
    number: 1-0-3
  s_right_wire_ramp_vuk_exit:
    platform: opp
    number: 1-0-2
  s_tower_ramp_entry:
    platform: opp
    number: 0-0-26
  s_tower_pensieve:
    platform: opp
    number: 1-0-26
  s_tower_pensieve_exit:
    platform: opp
    number: 1-0-20
  s_left_wire_ramp_exit:
    platform: opp
    number: 0-0-24
  # Subway opto's
  s_subway_vuk_left:
    platform: opp
    number: 1-0-22
  s_subway_vuk_left_buffer_chamber:
    platform: opp
    number: 1-0-24
  s_subway_vuk_left_buffer_1:
    platform: virtual
    number: 
  s_subway_vuk_left_buffer_2:
    platform: opp
    number: 1-0-29
  s_subway_vuk_right:
    platform: opp
    number: 1-0-30
  s_subway_vuk_right_buffer_1:
    platform: opp
    number: 0-0-8
  s_subway_vuk_right_buffer_2:
    platform: virtual
    number: 
  s_subway_vuk_selector:
    platform: opp
    number: 1-0-28