#config_version=6
lights:
  # OPP Main board NEO1 - Playfield
  # Backside above playfield
  l_ws2812_castle_door:
    number: 1-0-0
    subtype: led
    type: grb
    tags: target_lights
  # Right string
  l_ws2812_shot_right_orbit:
    number: 1-0-1
    subtype: led
    type: grb
    tags: shot_lights
  l_ws2812_mis_gringotts_bank:
    number: 1-0-2
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_mis_ravenclaw:
    number: 1-0-3
    subtype: led
    type: grb
    tags: house_lights
  l_ws2812_mis_gryffindor:
    number: 1-0-4
    subtype: led
    type: grb
    tags: house_lights
  l_ws2812_mis_hufflepuff:
    number: 1-0-5
    subtype: led
    type: grb
    tags: house_lights
  l_ws2812_mis_slytherin:
    number: 1-0-6
    subtype: led
    type: grb
    tags: house_lights
  l_ws2812_lightning_right:
    number: 1-0-7
    subtype: led
    type: grb
    tags: lightning_lights
  l_ws2812_mis_triwizard_tournament:
    number: 1-0-8
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_mis_unforgivable_cursus:
    number: 1-0-9
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_mis_hall_of_prophecy:
    number: 1-0-10
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_mis_order_of_the_phoenix:
    number: 1-0-11
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_shot_ministry:
    number: 1-0-12
    subtype: led
    type: grb
    tags: shot_lights
  l_ws2812_mis_ministry:
    number: 1-0-13
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_mis_daily_prophet:
    number: 1-0-14
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_lane_fl_right:
    number: 1-0-15
    subtype: led
    type: grb
    tags: lane_lights
  l_ws2812_lane_dr_right:
    number: 1-0-16
    subtype: led
    type: grb
    tags: lane_lights
  l_ws2812_skillshot:
    number: 1-0-17
    subtype: led
    type: grb
    tags: skill_shot_lights
  # Middle string 1
  l_ws2812_tar_wand:
    number: 1-0-18
    subtype: led
    type: grb
    tags: target_lights
  l_ws2812_shot_daigon:
    number: 1-0-19
    subtype: led
    type: grb
    tags: shot_lights
  l_ws2812_shot_gringots:
    number: 1-0-20
    subtype: led
    type: grb
    tags: shot_lights
  l_ws2812_tar_stone:
    number: 1-0-21
    subtype: led
    type: grb
    tags: target_lights
  l_ws2812_tar_cloak:
    number: 1-0-22
    subtype: led
    type: grb
    tags: target_lights
  l_ws2812_mis_chamber:
    number: 1-0-23
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_mis_basilisk:
    number: 1-0-24
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_shot_right_ramp:
    number: 1-0-25
    subtype: led
    type: grb
    tags: shot_lights
  l_ws2812_mis_spells:
    number: 1-0-26
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_mis_rubeus_hagrid:
    number: 1-0-27
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_mis_tower:
    number: 1-0-28
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_mis_dumbledores_office:
    number: 1-0-29
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_shot_left_ramp:
    number: 1-0-30
    subtype: led
    type: grb
    tags: shot_lights
  l_ws2812_tar_platform:
    number: 1-0-31
    subtype: led
    type: grb
    tags: target_lights
  l_ws2812_lightning_left:
    number: 1-0-32
    subtype: led
    type: grb
    tags: lightning_lights
  l_ws2812_lightning_bottom:
    number: 1-0-33
    subtype: led
    type: grb
    tags: lightning_lights
  l_ws2812_tar_nimbus:
    number: 1-0-34
    subtype: led
    type: grb
    tags: target_lights
  # Middle string 2
  l_ws2812_hor_book:
    number: 1-0-35
    subtype: led
    type: grb
    tags: horcrux_lights
  l_ws2812_hor_ring:
    number: 1-0-36
    subtype: led
    type: grb
    tags: horcrux_lights
  l_ws2812_hor_ring_destroy:
    number: 1-0-37
    subtype: led
    type: grb
    tags: horcrux_destroy_lights
  l_ws2812_hor_book_destroy:
    number: 1-0-38
    subtype: led
    type: grb
    tags: horcrux_destroy_lights
  l_ws2812_hor_neckles:
    number: 1-0-39
    subtype: led
    type: grb
    tags: horcrux_lights
  l_ws2812_voldemort:
    number: 1-0-40
    subtype: led
    type: grb
  l_ws2812_hor_cup:
    number: 1-0-41
    subtype: led
    type: grb
    tags: horcrux_lights
  l_ws2812_hor_cup_destroy:
    number: 1-0-42
    subtype: led
    type: grb
    tags: horcrux_destroy_lights
  l_ws2812_hor_neckles_destroy:
    number: 1-0-43
    subtype: led
    type: grb
    tags: horcrux_destroy_lights
  l_ws2812_hor_harry:
    number: 1-0-44
    subtype: led
    type: grb
    tags: horcrux_lights
  l_ws2812_hor_diadeem:
    number: 1-0-45
    subtype: led
    type: grb
    tags: horcrux_lights
  l_ws2812_hor_diadeem_destroy:
    number: 1-0-46
    subtype: led
    type: grb
    tags: horcrux_destroy_lights
  l_ws2812_hor_harry_destroy:
    number: 1-0-47
    subtype: led
    type: grb
    tags: horcrux_destroy_lights
  l_ws2812_hor_nagini:
    number: 1-0-48
    subtype: led
    type: grb
    tags: horcrux_lights
  l_ws2812_hor_nagini_destroy:
    number: 1-0-49
    subtype: led
    type: grb
    tags: horcrux_destroy_lights
  l_ws2812_shoot_again:
    number: 1-0-50
    subtype: led
    type: grb
  # Left string
  l_ws2812_shot_forrest:
    number: 1-0-51
    subtype: led
    type: grb
    tags: shot_lights 
  l_ws2812_mis_forrest:
    number: 1-0-52
    subtype: led
    type: grb 
    tags: mission_lights, theme_lights
  l_ws2812_shot_sword:
    number: 1-0-53
    subtype: led
    type: grb
    tags: shot_lights 
  l_ws2812_tar_sword:
    number: 1-0-54
    subtype: led
    type: grb
    tags: target_lights
  l_ws2812_shot_quidditch:
    number: 1-0-55
    subtype: led
    type: grb
    tags: shot_lights
  l_ws2812_mis_quidditch:
    number: 1-0-56
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_mis_goldensnitch:
    number: 1-0-57
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_tar_light_diagon_alley:
    number: 1-0-58
    subtype: led
    type: grb
    tags: target_lights
  l_ws2812_lane_fl_left:
    number: 1-0-59
    subtype: led
    type: grb
    tags: lane_lights
  l_ws2812_lane_dr_left:
    number: 1-0-60
    subtype: led
    type: grb
    tags: lane_lights