#config_version=6
lights:
  # OPP Main board NEO1 - Playfield
  # Backside above playfield
  l_ws2812_castle_door:
    number: 1-0-0
    subtype: led
    type: grb
    tags: target_lights
  # Right string
  l_ws2812_shot_right_orbit:
    previous: l_ws2812_castle_door
    subtype: led
    type: grb
    tags: shot_lights
  l_ws2812_mis_gringotts_bank:
    previous: l_ws2812_shot_right_orbit
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_mis_ravenclaw:
    previous: l_ws2812_mis_gringotts_bank
    subtype: led
    type: grb
    tags: house_lights
  l_ws2812_mis_gryffindor:
    previous: l_ws2812_mis_ravenclaw
    subtype: led
    type: grb
    tags: house_lights
  l_ws2812_mis_hufflepuff:
    previous: l_ws2812_mis_gryffindor
    subtype: led
    type: grb
    tags: house_lights
  l_ws2812_mis_slytherin:
    previous: l_ws2812_mis_hufflepuff
    subtype: led
    type: grb
    tags: house_lights
  l_ws2812_lightning_right:
    previous: l_ws2812_mis_slytherin
    subtype: led
    type: grb
    tags: lightning_lights
  l_ws2812_mis_triwizard_tournament:
    previous: l_ws2812_lightning_right
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_mis_unforgivable_cursus:
    previous: l_ws2812_mis_triwizard_tournament
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_mis_hall_of_prophecy:
    previous: l_ws2812_mis_unforgivable_cursus
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_mis_order_of_the_phoenix:
    previous: l_ws2812_mis_hall_of_prophecy
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_shot_ministry:
    previous: l_ws2812_mis_order_of_the_phoenix
    subtype: led
    type: grb
    tags: shot_lights
  l_ws2812_mis_ministry:
    previous: l_ws2812_shot_ministry
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_mis_daily_prophet:
    previous: l_ws2812_mis_ministry
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_lane_fl_right:
    previous: l_ws2812_mis_daily_prophet
    subtype: led
    type: grb
    tags: lane_lights
  l_ws2812_lane_dr_right:
    previous: l_ws2812_lane_fl_right
    subtype: led
    type: grb
    tags: lane_lights
  l_ws2812_skillshot:
    previous: l_ws2812_lane_dr_right
    subtype: led
    type: grb
    tags: skill_shot_lights
  # Middle string 1
  l_ws2812_tar_wand:
    previous: l_ws2812_skillshot
    subtype: led
    type: grb
    tags: target_lights
  l_ws2812_shot_daigon:
    previous: l_ws2812_tar_wand
    subtype: led
    type: grb
    tags: shot_lights
  l_ws2812_shot_gringots:
    previous: l_ws2812_shot_daigon
    subtype: led
    type: grb
    tags: shot_lights
  l_ws2812_tar_stone:
    previous: l_ws2812_shot_gringots
    subtype: led
    type: grb
    tags: target_lights
  l_ws2812_tar_cloak:
    previous: l_ws2812_tar_stone
    subtype: led
    type: grb
    tags: target_lights
  l_ws2812_mis_chamber:
    previous: l_ws2812_tar_cloak
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_mis_basilisk:
    previous: l_ws2812_mis_chamber
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_shot_right_ramp:
    previous: l_ws2812_mis_basilisk
    subtype: led
    type: grb
    tags: shot_lights
  l_ws2812_mis_spells:
    previous: l_ws2812_shot_right_ramp
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_mis_rubeus_hagrid:
    previous: l_ws2812_mis_spells
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_mis_tower:
    previous: l_ws2812_mis_rubeus_hagrid
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_mis_dumbledores_office:
    previous: l_ws2812_mis_tower
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_shot_left_ramp:
    previous: l_ws2812_mis_dumbledores_office
    subtype: led
    type: grb
    tags: shot_lights
  l_ws2812_tar_platform:
    previous: l_ws2812_shot_left_ramp
    subtype: led
    type: grb
    tags: target_lights
  l_ws2812_lightning_left:
    previous: l_ws2812_tar_platform
    subtype: led
    type: grb
    tags: lightning_lights
  l_ws2812_lightning_bottom:
    previous: l_ws2812_lightning_left
    subtype: led
    type: grb
    tags: lightning_lights
  l_ws2812_tar_nimbus:
    previous: l_ws2812_lightning_bottom
    subtype: led
    type: grb
    tags: target_lights
  # Middle string 2
  l_ws2812_hor_book:
    previous: l_ws2812_tar_nimbus
    subtype: led
    type: grb
    tags: horcrux_lights
  l_ws2812_hor_ring:
    previous: l_ws2812_hor_book
    subtype: led
    type: grb
    tags: horcrux_lights
  l_ws2812_hor_ring_destroy:
    previous: l_ws2812_hor_ring
    subtype: led
    type: grb
    tags: horcrux_destroy_lights
  l_ws2812_hor_book_destroy:
    previous: l_ws2812_hor_ring_destroy
    subtype: led
    type: grb
    tags: horcrux_destroy_lights
  l_ws2812_hor_neckles:
    previous: l_ws2812_hor_book_destroy
    subtype: led
    type: grb
    tags: horcrux_lights
  l_ws2812_voldemort:
    previous: l_ws2812_hor_neckles
    subtype: led
    type: grb
  l_ws2812_hor_cup:
    previous: l_ws2812_voldemort
    subtype: led
    type: grb
    tags: horcrux_lights
  l_ws2812_hor_cup_destroy:
    previous: l_ws2812_hor_cup
    subtype: led
    type: grb
    tags: horcrux_destroy_lights
  l_ws2812_hor_neckles_destroy:
    previous: l_ws2812_hor_cup_destroy
    subtype: led
    type: grb
    tags: horcrux_destroy_lights
  l_ws2812_hor_harry:
    previous: l_ws2812_hor_neckles_destroy
    subtype: led
    type: grb
    tags: horcrux_lights
  l_ws2812_hor_diadeem:
    previous: l_ws2812_hor_harry
    subtype: led
    type: grb
    tags: horcrux_lights
  l_ws2812_hor_diadeem_destroy:
    previous: l_ws2812_hor_diadeem
    subtype: led
    type: grb
    tags: horcrux_destroy_lights
  l_ws2812_hor_harry_destroy:
    previous: l_ws2812_hor_diadeem_destroy
    subtype: led
    type: grb
    tags: horcrux_destroy_lights
  l_ws2812_hor_nagini:
    previous: l_ws2812_hor_harry_destroy
    subtype: led
    type: grb
    tags: horcrux_lights
  l_ws2812_hor_nagini_destroy:
    previous: l_ws2812_hor_nagini
    subtype: led
    type: grb
    tags: horcrux_destroy_lights
  l_ws2812_shoot_again:
    previous: l_ws2812_hor_nagini_destroy
    subtype: led
    type: grb
  # Left string
  l_ws2812_shot_forrest:
    previous: l_ws2812_shoot_again
    subtype: led
    type: grb
    tags: shot_lights 
  l_ws2812_mis_forrest:
    previous: l_ws2812_shot_forrest
    subtype: led
    type: grb 
    tags: mission_lights, theme_lights
  l_ws2812_shot_sword:
    previous: l_ws2812_mis_forrest
    subtype: led
    type: grb
    tags: shot_lights 
  l_ws2812_tar_sword:
    previous: l_ws2812_shot_sword
    subtype: led
    type: grb
    tags: target_lights
  l_ws2812_shot_quidditch:
    previous: l_ws2812_tar_sword
    subtype: led
    type: grb
    tags: shot_lights
  l_ws2812_mis_quidditch:
    previous: l_ws2812_shot_quidditch
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_mis_goldensnitch:
    previous: l_ws2812_mis_quidditch
    subtype: led
    type: grb
    tags: mission_lights, theme_lights
  l_ws2812_tar_light_diagon_alley:
    previous: l_ws2812_mis_goldensnitch
    subtype: led
    type: grb
    tags: target_lights
  l_ws2812_lane_fl_left:
    previous: l_ws2812_tar_light_diagon_alley
    subtype: led
    type: grb
    tags: lane_lights
  l_ws2812_lane_dr_left:
    previous: l_ws2812_lane_fl_left
    subtype: led
    type: grb
    tags: lane_lights