#config_version=6
config:
  - hardware_opp_coils.yaml
  - hardware_opp_lights.yaml
  - hardware_opp_servos.yaml
  - hardware_opp_switches.yaml
  - hardware_fadecandy.yaml
  - hardware_pololu.yaml
  - hardware_rpi.yaml

hardware:
  platform: opp, fadecandy, pololu_maestro, rpi, virtual
  # OPP board revision
  driverboards: gen2
  lights: opp, fadecandy

opp:
  ports: /dev/ttyOPP-0, /dev/ttyOPP-1, /dev/ttyOPP-2, /dev/ttyOPP-3, /dev/ttyOPP-4
  chains:
    0: /dev/ttyOPP-0
    1: /dev/ttyOPP-1
    2: /dev/ttyOPP-2
    3: /dev/ttyOPP-3
    4: /dev/ttyOPP-4
  debug: true