#config_version=6
lights:
  # OPP Main board NEO3 - Playfield
  l_playfield_left:
    number: 3-0-0
    subtype: led
    type: grb
    tags: playfield_left
  l_sling_left_1:
    previous: l_playfield_left
    subtype: led
    type: grb
    tags: sling_left
  l_sling_left_2:
    previous: l_sling_left_1
    subtype: led
    type: grb
    tags: sling_left
  l_lane_left_1:
    previous: l_sling_left_2
    subtype: led
    type: grb
    tags: lane_left
  l_lane_left_2:
    previous: l_lane_left_1
    subtype: led
    type: grb
    tags: lane_left
  l_lane_right_1:
    previous: l_lane_left_2
    subtype: led
    type: grb
    tags: lane_right
  l_lane_right_2:
    previous: l_lane_right_1
    subtype: led
    type: grb
    tags: lane_right
  l_sling_right_1:
    previous: l_lane_right_2
    subtype: led
    type: grb
    tags: sling_right
  l_sling_right_2:
    previous: l_sling_right_1
    subtype: led
    type: grb
    tags: sling_right
  l_playfield_right:
    previous: l_sling_right_2
    subtype: led
    type: grb
    tags: playfield_right