#config_version=5
keyboard:
  s:
    switch: s_start_button
  z:
    switch: s_fl_left_a
  /:
    switch: s_fl_right_a
  x:
    switch: s_sling_left
  d:
    switch: s_drain
  p:
    switch: s_plunger_lane
  e:
    switch: s_service_enter
  left:
    switch: s_service_esc
  up:
    switch: s_service_up
  down:
    switch: s_service_down