#config_version=5
mode:           
  start_events: start_mode_field_castle_level_1
  stop_events: stop_mode_field_castle_level_1
  priority: 300

config:
  - field_castle_level_1_slides.yaml

# hit door to lit
# hit again and let magnet grap the ball
# when grabbed open will be opened
# when shot is made the door will closed
# when missed door will be left open until shot is made
# reset shot
shots:
  sh_castle_door:
    advance_events: sh_core_castle_door_hit
    profile: sp_castle_door
    show_tokens:
      led: l_ws2812_castle_door
      color_name: flames
  sh_castle_main_entrance:
    advance_events: sh_core_castle_main_entrance_hit
    profile: sp_castle_main_entrance
  sh_castle_part_1_clock_tower:
    advance_events: sh_core_castle_main_entrance_hit
    profile: sp_castle_part_1_ct
  sh_castle_part_2_forbidden_forest:
    advance_events: sh_core_castle_main_entrance_hit
    profile: sp_castle_part_2_ff



shot_profiles:
  sp_castle_door:
    advance_on_hit: false
    states:
      - name: unlit
        show: flames
        sync_ms: 500
      - name: lit
        show: flash_normal
        sync_ms: 500
      - name: open
        show: flash_heartbeat
        sync_ms: 500
  sp_castle_main_entrance:
    advance_on_hit: false
    states:
      - name: unlit
      - name: lit
  sp_castle_part_1_ct:
    advance_on_hit: false
    states:
      - name: unlit
      - name: lit
  sp_castle_part_2_ff:
    advance_on_hit: false
    states:
      - name: unlit
      - name: lit

state_machines:
  sm_castle_level_1_progress:
    starting_state: part_1
    persist_state: true
    states:
      part_1:
        label: Albus Dumbledore
      part_2:
        label: Forbidden Forest
      part_3:
        label: You know who
    transitions:
      - source: part_1
        target: part_2
        events: level_1_part_completed, test_event
      - source: part_2
        target: part_3
        events: level_1_part_completed, test_event

slide_player:
  # this shows a slide on mode start. This is for test purpuse.
  mode_field_castle_level_1_started{device.state_machines.sm_castle_level_1_progress.state == 'part_1'}: 
    sl_part_1:
      expire: 3s
  mode_field_castle_level_1_started{device.state_machines.sm_castle_level_1_progress.state == 'part_2'}: 
    sl_part_2:
      expire: 3s
  mode_field_castle_level_1_started{device.state_machines.sm_castle_level_1_progress.state == 'part_3'}: 
    sl_part_3:
      expire: 3s
