#config_version=5
mode:
    start_events: start_mode_field_chamber_of_secrets
    stop_events: stop_mode_field_chamber_of_secrets
    priority: 310


shot_profiles:

    sp_chamber:
        #advance_on_hit: false
        states:
          - name: unlit
            show: light_off
          - name: lit
            show: flash_normal
          - name: played
            show: light_on

shots:

    sh_chamber_of_secrets:
        hit_events: sh_core_chamber_hit
        profile: sp_chamber
        show_tokens:
            led: l_ws2812_mis_chamber
            color_name: red