#config_version=5

# Main slide center position is as follows;
# x: left+575     # (x = 1250 - 100 = 1150)
# y: top-315      # (y =  700 -  70 =  630)
# anchor_x: middle
# anchor_y: middle

# -------------
#  Mode Slides
# -------------
slides:
  sl_spells_light_qualify_counter:
    widgets:
    - type: text
      font_name: harry-potter
      text: (var_mc_qualify_spell_name)
      font_size: 120
      color: score_text_default
      x: left+575
      y: top-100
      anchor_x: middle
      anchor_y: middle
    - type: text
      font_name: harry-potter
      text: Ramp Shots
      font_size: 80
      color: score_text_default
      x: left+575
      y: top-280
      anchor_x: middle
      anchor_y: middle
    - type: text
      font_name: harry-potter
      text: (var_mc_qualify_spells_counter_progress) of (var_mc_qualify_spells_counter_target)
      font_size: 50
      color: score_text_default
      x: left+575
      y: top-375
      anchor_x: middle
      anchor_y: middle
    - widget: widget_main_back_(current_player.house_theme_name)
  sl_spells_light_qualify_lit:
    widgets:
    - type: text
      font_name: harry-potter
      text: Spells Light Lit
      font_size: 80
      color: score_text_default
      x: left+575
      y: top-100
      anchor_x: middle
      anchor_y: middle
    - widget: widget_main_back_(current_player.house_theme_name)