#config_version=5

# For Spell 1
# * Make 10 Ramp Shots to lit the Spells Light Qualification
# * Make another Ramp Shot to activate Spells Light Qualification and lit the Right Ramp Light (maybe later also Orbit Shot lights)
# * A 10 seconds timer starts to complete Spells Light Qualification
# - Before timer ends make another right ramp shot and collect bonus level
# * State machine levels up when timer ends or when qualifying completes

mode:           
  start_events: start_mode_field_spells_ramp
  stop_events: stop_mode_field_spells_ramp
  priority: 300

config:
  - field_spells_ramp_slides.yaml

sequence_shots:
  sq_shot_spells_ramp:
    switch_sequence: s_spells_ramp_entry, s_right_wire_ramp_small
    sequence_timeout: 3s

shots:
  sh_right_ramp_light:
    enable_events: mode_field_spells_ramp_started
    disable_events: mode_field_spells_ramp_will_stop
    restart_events: 
      - timer_right_ramp_light_qualify_timer_complete
      - mode_field_spells_ramp_will_stop
    advance_events: sq_shot_spells_ramp_hit{device.shots.sh_spells_light.state_name == 'lit'}
    profile: sp_right_ramp_light
    show_tokens:
      led: l_ws2812_shot_right_ramp
      color_name: yellow
  sh_spells_light:
    enable_events: mode_field_spells_ramp_started
    disable_events: mode_field_spells_ramp_will_stop
    restart_events: 
      - timer_right_ramp_light_qualify_timer_complete
      - ball_drain{device.shots.sh_right_ramp_light.state_name == 'lit'}
    advance_events: 
      - lb_spells_light_qualify_counter_completed
      - timer_right_ramp_light_qualify_timer_started
    profile: sp_spells_light
    show_tokens:
      led: l_ws2812_mis_spells
      color_name: (current_player.house_theme_led)

shot_profiles:
  sp_right_ramp_light:
    advance_on_hit: false
    states:
      - name: unlit
        show: light_off
        sync_ms: 500
      - name: lit
        show: flash_normal
        sync_ms: 500
  sp_spells_light:
    advance_on_hit: false
    states:
      - name: unlit
        show: light_off
        sync_ms: 500
      - name: lit
        show: flash_normal
        sync_ms: 500
      - name: active
        show: flash_slow
        sync_ms: 500

counters:
  lb_spells_light_qualify_counter:
    count_events: sq_shot_spells_ramp_hit
    count_complete_value: 10
    start_enabled: true
    persist_state: true
    disable_on_complete: true
    restart_events: 
      - timer_right_ramp_light_qualify_timer_complete
      - ball_drain{device.shots.sh_right_ramp_light.state_name == 'lit'}
    events_when_complete: lb_spells_light_qualify_counter_completed, test

timers:
  right_ramp_light_qualify_timer:
    start_value: 0
    end_value: 15
    direction: up
    control_events:
      - action: start
        event: sq_shot_spells_ramp_hit{device.shots.sh_spells_light.state_name == 'lit'}
      - action: reset
        event: timer_right_ramp_light_qualify_timer_complete

state_machines:
  sm_spells_level:
    persist_state: true
    starting_state: Spell 1
    states:
      Spell 1:
        label:
      Spell 2:
        label:
      Spell 3:
        label:
      Spell 4:
        label:
      Spell 5:
        label:
    transitions:
      - source: Spell 1
        target: Spell 2
        events: 
          - timer_right_ramp_light_qualify_timer_complete
          - ball_drain{device.shots.sh_right_ramp_light.state_name == 'lit'}
      - source: Spell 2
        target: Spell 3
        events:  
          - timer_right_ramp_light_qualify_timer_complete
          - ball_drain{device.shots.sh_right_ramp_light.state_name == 'lit'}
      - source: Spell 3
        target: Spell 4
        events:  
          - timer_right_ramp_light_qualify_timer_complete
          - ball_drain{device.shots.sh_right_ramp_light.state_name == 'lit'}
      - source: Spell 4
        target: Spell 5
        events:  
          - timer_right_ramp_light_qualify_timer_complete
          - ball_drain{device.shots.sh_right_ramp_light.state_name == 'lit'}

variable_player:
  mode_field_spells_ramp_started:
    var_qualify_spells_counter_target:
      action: set
      int: 10 # replace later with counter complet value setting
    var_qualify_spell: # see also below 
      action: set
      string: (device.state_machines.sm_spells_level.state)
  logicblock_lb_spells_light_qualify_counter_hit{device.shots.sh_spells_light.state_name == 'unlit'}:
    # using for displaying
    var_qualify_spells_counter: 
      int: device.counters.lb_spells_light_qualify_counter.value
      action: set
  lb_spells_light_qualify_counter_completed:    # using for displaying
    var_qualify_spells_counter: 
      int: 10 #settings.x_counter
      action: set
    var_qualify_spell: # see also above
      action: set
      string: (device.state_machines.sm_spells_level.state)
      
slide_player:
  # Give status of Spells level and Qualify counter on display
  logicblock_lb_spells_light_qualify_counter_hit{device.shots.sh_spells_light.state_name == 'unlit'}:
    sl_spells_light_qualify_counter:
      expire: 3s